package com.java.liuyun;

import android.os.Bundle;
import android.view.View;
import android.widget.ExpandableListView;

import androidx.appcompat.app.AppCompatActivity;

import java.util.ArrayList;
import java.util.List;

public class NewsClusterActivity extends AppCompatActivity {

    private ExpandableListView expandableListView;
    private List<String> categoryNames, categorySizes;
    private List<List<AtlasData>> atlasItems; //改成AtlasData类（包含两个字符串）
    private List<AtlasData> items;

    public NewsClusterActivity() {
        categoryNames = new ArrayList<>();
        categorySizes = new ArrayList<>();
        atlasItems = new ArrayList<>();
    }

    public void initView() {
        categoryNames.add("[疫苗][试验][临床]");
        categoryNames.add("[研究][病毒][感染]");
        categoryNames.add("[患者][研究][covid]");
        categoryNames.add("[瑞德][试验][西韦]");
        categoryNames.add("[研究][细胞][肺炎]");
        categoryNames.add("[病毒][新冠][研究]");
        categoryNames.add("[新冠][病毒][美国]");
        categoryNames.add("[病毒][研究][冠状病毒]");
        categoryNames.add("[疫情][攻关][科技]");
        categoryNames.add("[病毒][研究][新冠]");
        categorySizes.add("60");
        categorySizes.add("132");
        categorySizes.add("90");
        categorySizes.add("26");
        categorySizes.add("59");
        categorySizes.add("103");
        categorySizes.add("68");
        categorySizes.add("60");
        categorySizes.add("29");
        categorySizes.add("72");
        items = new ArrayList<>();
        atlasItems.add(items);
        items.add(new AtlasData("沈阳同联集团公司研...", "http://www.ln.chinanews.com/news/2020/0328/264926.html"));
        items.add(new AtlasData("中国工程院院士黄璐...", "https://3g.163.com/news/article_cambrian/F8HGB0RK0514M5JU.html"));
        items.add(new AtlasData("中国重组新型冠状病...", "https://baijiahao.baidu.com/s?id=1661814813636157464&wfr=spider&for=pc"));
        items.add(new AtlasData("军事科学院军事医学...", "http://www.mod.gov.cn/topnews/2020-03/17/content_4862066.htm?from=timeline&isappinstalled=0"));
        items.add(new AtlasData("当地时间3月16日...", "https://www.cn-healthcare.com/article/20200317/content-532743.html"));
        items.add(new AtlasData("上海市科委主任张全...", "https://www.yicai.com/news/100550209.html"));
        items.add(new AtlasData("复星医药宣布联手m...", "https://m.yicai.com/news/100549446.html"));
        items.add(new AtlasData("华中科技大当前科研...", "1.抗体快速检测试剂盒，一滴血15分钟出结果"));
        items.add(new AtlasData("新冠肺炎疫情科研五...", "1.在病毒病原和流行病学研究"));
        items.add(new AtlasData("新冠肺炎当前检测诊...", "已经有14个检测产品获批并应用于临床，整体检测水平显著提高，能满足国内诊断检测的需求。抗体和核酸两类检测的试剂互相补充，进一步提高检出率。"));
        items.add(new AtlasData("新冠肺炎当前临床救...", "科技攻关的一批药物和救治技术已在疾病救治当中扩大应用，磷酸氯喹、托珠单抗、中医药当中的有关方剂和注射液等一批推荐的药物以及康复者血浆、血液净化治疗这样一些治疗方法也纳入到诊疗方案，正在积极推动干细胞、单克隆抗体等先进技术用于危重症患者治疗研究。通过临床实践制定了分型分层的治疗策略，不断优化治疗方案，其中就包括阻断轻型、普通型向重症转化的治疗方案，也包括重型、危重型患者的救治方案。"));
        items.add(new AtlasData("新冠肺炎当前疫情防...", "科技部等13个部门组建了国务院联防联控机制科技攻关组设立了疫苗研发专班，第一批筛选了8家机构确立了9项任务，沿着灭活疫苗、基因工程重组的亚单位疫苗、腺病毒载体疫苗、减毒流感病毒载体疫苗、核酸疫苗等五条技术路线推进疫苗攻关工作。人工智能和大数据技术也在疫情防控当中广泛地被应用。"));
        items.add(new AtlasData("以色列科技部27日...", "https://www.yicai.com/news/100526121.html"));
        items.add(new AtlasData("新型冠状病毒的疫苗...", "https://www.linkresearcher.com/information/aba66141-44bc-423d-8d4f-04aa2dde6ea5"));
        items.add(new AtlasData("国制药公司Mode...", "https://mp.weixin.qq.com/s/nkYdb36d4_CpX2GvHAwlUA"));
        items.add(new AtlasData("浙江官宣新冠肺炎疫...", "http://scitech.people.com.cn/n1/2020/0224/c1007-31600477.html"));
        items.add(new AtlasData("卫健委回应在疫苗研...", "https://m.yicai.com/news/100515742.html"));
        items.add(new AtlasData("赛诺菲全球疫苗事业...", "https://m.yicai.com/news/100512287.html"));
        items.add(new AtlasData("中国目前有80项针...", "https://www.nature.com/articles/d41586-020-00444-3"));
        items.add(new AtlasData("中国科研团队宣布，...", "http://www.chinanews.com/gn/2020/02-10/9085525.shtml"));
        items.add(new AtlasData("德国“痊愈”疫苗公...", "https://www.yicai.com/news/100572990.html"));
        items.add(new AtlasData("清华大学张林琦团队...", "http://sa.sogou.com/sgsearch/sgs_tc_news.php?req=oHNUrFdHxWjBQwRquvZVyrtP-wHQWf386ivFAGW5gbQ=&f_type=feed"));
        items.add(new AtlasData("加州大学戴维斯分校...", "https://mp.weixin.qq.com/s/ocXFbPyJtyC77BBkUbj91g"));
        items.add(new AtlasData("中国工程院院士陈志...", "http://www.caixin.com/2020-04-01/101537368.html"));
        items.add(new AtlasData("强生公司于2020...", "http://www.sci666.com.cn/47113.html"));
        items.add(new AtlasData("德...", ""));
        items.add(new AtlasData("清华团队研发获进展...", "http://news.sina.com.cn/c/2020-04-02/doc-iimxxsth3174598.shtml"));
        items.add(new AtlasData("以中国中医科学院院...", "https://new.qq.com/omn/20200329/20200329A0IEGQ00.html"));
        items.add(new AtlasData("美国《科学》杂志当...", "此外，高福院士还对病毒是否起源于武汉华南海鲜市场、中国分享病毒数据是否及时、疫苗和药物研制进程等关键问题，作出了解答。"));
        items.add(new AtlasData("陈薇院士团队研制的...", "https://www.360kuai.com/pc/98ca092c9697d4aab?cota=3&kuai_so=1&sign=360_e39369d1&refer_scene=so_54"));
        items.add(new AtlasData("3 月 17 日，...", "已知的是，这是国内第一个进入临床试验的新冠疫苗，受试者招募已经同步展开"));
        items.add(new AtlasData("3月16日，军事科...", "http://news.sciencenet.cn/htmlnews/2020/4/437893.shtm"));
        items.add(new AtlasData("西班牙研究团队提出...", "https://mp.weixin.qq.com/s/4NOJ_n8hvqY2s9E6Gpwz4w"));
        items.add(new AtlasData("北卡罗来纳大学教堂...", "https://mp.weixin.qq.com/s/CZd_Cag-RbbkxUmZ_4UlVg"));
        items.add(new AtlasData("康希诺生物股份公司...", "http://www.caixin.com/2020-04-10/101540847.html"));
        items.add(new AtlasData("牛津大学疫苗学教授...", "http://news.sciencenet.cn/htmlnews/2020/4/438256.shtm"));
        items.add(new AtlasData("由军事科学院军事医...", "https://www.thepaper.cn/newsDetail_forward_6951424"));
        items.add(new AtlasData("由国药集团中国生物...", "http://news.sciencenet.cn/htmlnews/2020/4/438338.shtm"));
        items.add(new AtlasData("日本富士胶片公司表...", "https://baijiahao.baidu.com/s?id=1663911643151652734&wfr=spider&for=pc"));
        items.add(new AtlasData("德国生物技术公司B...", "https://mp.weixin.qq.com/s/re1fLHuhUPNGLIYQKld-Eg"));
        items.add(new AtlasData("中国两款新冠病毒灭...", "https://www.yicai.com/news/100591999.html"));
        items.add(new AtlasData("国际欧亚科学院院士...", "https://www.thepaper.cn/newsDetail_forward_7016950"));
        items.add(new AtlasData("瑞士制药商诺华公司...", "https://www.thepaper.cn/newsDetail_forward_7066029"));
        items.add(new AtlasData("由国药集团中国生物...", "https://www.yicai.com/news/100608089.html"));
        items.add(new AtlasData("德国卫生部和疫苗审...", "https://www.thepaper.cn/newsDetail_forward_7100280"));
        items.add(new AtlasData("英国政府将向牛津团...", "https://www.yicai.com/news/100603916.html"));
        items.add(new AtlasData("中国生物宣布，新冠...", "http://www.caixin.com/2020-04-25/101546993.html"));
        items.add(new AtlasData("中国生物北京生物制...", "http://finance.ifeng.com/c/7w2MFBKZ9AM"));
        items.add(new AtlasData("加拿大卫生部受理我...", "https://www.thepaper.cn/newsDetail_forward_7181307"));
        items.add(new AtlasData("中国科学技术大学研...", "https://mp.weixin.qq.com/s/eDpwcs9-23KKNp1K5_xLxQ"));
        items.add(new AtlasData("由军事科学院军事医...", "https://www.thepaper.cn/newsDetail_forward_7005458"));
        items.add(new AtlasData("以色列生物研究所在...", "http://news.sciencenet.cn/htmlnews/2020/5/439369.shtm"));
        items.add(new AtlasData("美国制药巨头辉瑞生...", "https://www.thepaper.cn/newsDetail_forward_7276005"));
        items.add(new AtlasData("英国南安普顿大学医...", "http://news.sciencenet.cn/htmlnews/2020/5/439389.shtm"));
        items.add(new AtlasData("香港大学研究人员研...", "http://news.sciencenet.cn/htmlnews/2020/5/439522.shtm"));
        items.add(new AtlasData("中国生物董事长、科...", "https://www.thepaper.cn/newsDetail_forward_7407819"));
        items.add(new AtlasData("中国疫苗厂商科兴生...", "https://www.yicai.com/news/100633688.html"));
        items.add(new AtlasData("美国mRNA技术公...", "https://baijiahao.baidu.com/s?id=1667095069776631809&wfr=spider&for=pc"));
        items.add(new AtlasData("美国哈佛大学医学院...", "https://www.thepaper.cn/newsDetail_forward_7493450"));
        items.add(new AtlasData("美国癌症研究所研究...", "https://mp.weixin.qq.com/s/692oypzEjRkZxKy5lA8zhg"));
        items = new ArrayList<>();
        atlasItems.add(items);
        items.add(new AtlasData("宁波市疾病预防控制...", "https://www.yicai.com/news/100569749.html"));
        items.add(new AtlasData("武汉大学杨菁团队发...", "https://mp.weixin.qq.com/s/pqugeoJJQQHbjG38TDyR_A"));
        items.add(new AtlasData("欧洲疾病预防和控制...", "https://www.yicai.com/news/100568411.html"));
        items.add(new AtlasData("中国疾病预防控制中...", "https://mp.weixin.qq.com/s/snC24H4_ZrbpPygqJykRiA"));
        items.add(new AtlasData("北京师范大学研究团...", "https://mp.weixin.qq.com/s/kY1VL4g8yjXSp3VyycpHmQ"));
        items.add(new AtlasData("华中科技大学附属同...", "https://mp.weixin.qq.com/s/zH6uMVzCReLdpHmlKr_zAQ"));
        items.add(new AtlasData("中国科学院微生物研...", "https://mp.weixin.qq.com/s/Sd9_42Jw9kWc5sBa4yT9zg"));
        items.add(new AtlasData("美国北卡罗来纳大学...", "https://mp.weixin.qq.com/s/HsMkaVYZCPjj6Nav2FYM_Q"));
        items.add(new AtlasData("中山大学团队等研究...", "https://www.yicai.com/news/100558769.html"));
        items.add(new AtlasData("中山大学研究团队发...", "http://www.sci666.com.cn/45048.html"));
        items.add(new AtlasData("武汉儿童医院等机构...", "https://mp.weixin.qq.com/s/CgQVNFMOpTj6f22n20MrWg"));
        items.add(new AtlasData("复旦大学等机构研究...", "http://www.sci666.com.cn/44554.html"));
        items.add(new AtlasData("中国医学科学院医学...", "https://search.weixin.qq.com/k/Q1ZQX1BDalxbQFBUQFVQa0VWRk5eakdWVF5tR1dSb1VYWyRHUTdRVERv#wechat_redirect"));
        items.add(new AtlasData("多篇研究显示：儿童...", "http://www.caixin.com/2020-03-17/101529659.html"));
        items.add(new AtlasData("国医学科学院医学动...", "https://mp.weixin.qq.com/s/EPIGKlmdXqUTm4BshCXNdw"));
        items.add(new AtlasData("中国医学科学院医学...", "http://www.sci666.com.cn/43973.html"));
        items.add(new AtlasData("美国马里兰大学分析...", "http://www.sci666.com.cn/43688.html"));
        items.add(new AtlasData("美国马里兰大学等机...", "https://www.yicai.com/news/100548984.html"));
        items.add(new AtlasData("广州市妇女儿童医疗...", "https://www.yicai.com/news/100547862.html"));
        items.add(new AtlasData("新加坡国家传染病中...", "https://mp.weixin.qq.com/s/YaXk_BMDDeklh5qDu_8L3A"));
        items.add(new AtlasData("《科学》杂志日前发...", "http://www.caixin.com/2020-03-13/101527825.html"));
        items.add(new AtlasData("中国疾病预防控制中...", "https://mp.weixin.qq.com/s/0_dvF2qdqXhJXBvwu22eRw"));
        items.add(new AtlasData("香港大学的流行病学...", "http://www.sci666.com.cn/43124.html"));
        items.add(new AtlasData("武汉华南市场疫情的...", "https://www.linkresearcher.com/information/fbadcea9-db15-4d8c-9c78-c264c9f0c0f7"));
        items.add(new AtlasData("我国学者发现SAR...", "http://www.sci666.com.cn/41791.html"));
        items.add(new AtlasData("吴云涛、郑志明、黄...", "https://mp.weixin.qq.com/s/AkmGOSuGlxlYXkRAjFUDzQ"));
        items.add(new AtlasData("香港渔农自然护理署...", "https://mp.weixin.qq.com/s/imt7ie09DVyl6kJfiU5NFw"));
        items.add(new AtlasData("新型冠状病毒（CO...", "https://www.sciencedirect.com/science/article/pii/S1201971220301193"));
        items.add(new AtlasData("美国西南医学中心研...", "http://www.sci666.com.cn/40028.html"));
        items.add(new AtlasData("中山大学公共卫生学...", "http://www.sci666.com.cn/39561.html"));
        items.add(new AtlasData("广东疾控中心、珠海...", "https://m.yicai.com/news/100515226.html"));
        items.add(new AtlasData("德国吕贝克大学的R...", "https://www.dhakatribune.com/long-form/2020/02/18/in-the-thick-of-it-all"));
        items.add(new AtlasData("非洲首次发现感染，...", "https://www.nature.com/articles/d41586-020-00154-w"));
        items.add(new AtlasData("美国 CDC 发布...", "https://www.cdc.gov/mmwr/volumes/69/wr/mm6906e1.htm?s_cid=mm6906e1_w#contribAff"));
        items.add(new AtlasData("国家卫健委发布《新...", "http://news.youth.cn/jsxw/202002/t20200205_12186273.htm"));
        items.add(new AtlasData("旦大学陆路等研究人...", "https://mp.weixin.qq.com/s/Bm___X9hnSfcLfgvg77ABg"));
        items.add(new AtlasData("解放军中部战区总医...", "http://news.sciencenet.cn/htmlnews/2020/3/437659.shtm"));
        items.add(new AtlasData("中国医学科学院医学...", "https://www.yicai.com/news/100574931.html"));
        items.add(new AtlasData("复旦大学陆路等研究...", "https://mp.weixin.qq.com/s/Bm___X9hnSfcLfgvg77ABg"));
        items.add(new AtlasData("德国的科研团队研究...", "https://mp.weixin.qq.com/s/P9msk6MpHjhMlC14TUx__g"));
        items.add(new AtlasData("陆军军医大学王军平...", "https://mp.weixin.qq.com/s/BOta1Jvmcv325UO_07qUJA"));
        items.add(new AtlasData("南京医科大学沈洪兵...", "https://mp.weixin.qq.com/s/uy1K1FgsCLSP_-zzvD2rhQ"));
        items.add(new AtlasData("南加州大学医学中心...", "https://mp.weixin.qq.com/s/wG6sZq6Btvd0sia8r7E27g"));
        items.add(new AtlasData("德国红十字会献血部...", "https://www.yicai.com/news/100576205.html"));
        items.add(new AtlasData("德国柏林沙里泰大学...", "http://news.sciencenet.cn/htmlnews/2020/4/437817.shtm"));
        items.add(new AtlasData("教育部和驻外使领馆...", "http://news.sciencenet.cn/htmlnews/2020/4/437836.shtm"));
        items.add(new AtlasData("吴尊友：研究发现无...", "http://news.sina.com.cn/o/2020-04-02/doc-iimxxsth3288446.shtml"));
        items.add(new AtlasData("中山大学公共卫生学...", "https://3g.163.com/news/article_cambrian/F8JI3KO10514RM05.html"));
        items.add(new AtlasData("王茂团队收集了在1...", "http://www.inewsweek.cn/viewpoint/2020-03-18/8870.shtml"));
        items.add(new AtlasData("王茂团队收集了1月...", "http://www.chinanews.com/gn/2020/03-15/9126147.shtml"));
        items.add(new AtlasData("中山大学公共卫生学...", "https://3g.163.com/ent/article_cambrian/F7G36DD50514DUS7.html"));
        items.add(new AtlasData("中山大学医学院院长...", "https://tech.sina.com.cn/roll/2020-02-15/doc-iimxxstf1618293.shtml"));
        items.add(new AtlasData("美国明尼苏达大学传...", "https://www.360kuai.com/pc/9cbfe1a65553070fd?cota=3&kuai_so=1&sign=360_da20e874&refer_scene=so_3"));
        items.add(new AtlasData("乔杰：尚无母婴垂直...", "http://news.sciencenet.cn/htmlnews/2020/3/437268.shtm"));
        items.add(new AtlasData("德国夏里特医学院研...", "http://news.sciencenet.cn/htmlnews/2020/4/437867.shtm"));
        items.add(new AtlasData("南京医科大学刘云等...", "https://mp.weixin.qq.com/s/GiHzt26WJLx82k8G1vOzzw"));
        items.add(new AtlasData("德国研究团队研究发...", "http://sa.sogou.com/sgsearch/sgs_tc_news.php?req=61wApIY8u-8kJ4nVlthC_AM-PU2KBEDe6UWqEtBGP5k=&tencentdocid=20200404A0D9RV00&f_type=feed"));
        items.add(new AtlasData("西班牙研究团队研究...", "http://www.sci666.com.cn/47546.html"));
        items.add(new AtlasData("中科院武汉病毒所石...", "http://www.sci666.com.cn/47519.html"));
        items.add(new AtlasData("中国农业科学院哈尔...", "http://www.sci666.com.cn/47519.html"));
        items.add(new AtlasData("美国约翰斯·霍普金...", "https://www.yicai.com/news/100582076.html"));
        items.add(new AtlasData("中国疾病控制中心（...", "https://www.yicai.com/news/100583142.html"));
        items.add(new AtlasData("湖北省武汉市疾控中...", "http://news.sciencenet.cn/htmlnews/2020/4/438080.shtm"));
        items.add(new AtlasData("中国农科院哈尔滨兽...", "https://mp.weixin.qq.com/s/-EfUCzuEFSbgxk7ObhUcmA"));
        items.add(new AtlasData("香港大学李嘉诚医学...", "https://mp.weixin.qq.com/s/U7hZWgRBBmt9nBSE7J21Zg"));
        items.add(new AtlasData("中国中医科学院研究...", "https://mp.weixin.qq.com/s/HCmQM6AwgI4W52d2_cYAQg"));
        items.add(new AtlasData("美国南加州大学公共...", "https://www.thepaper.cn/newsDetail_forward_6939872"));
        items.add(new AtlasData("华中科技大学邬堂春...", "https://mp.weixin.qq.com/s/bnsSzDpf_NWU3qj_Hk3odA"));
        items.add(new AtlasData("哈佛大学研究发现生...", "http://news.sciencenet.cn/htmlnews/2020/4/438341.shtm"));
        items.add(new AtlasData("复旦大学上海公共卫...", "https://mp.weixin.qq.com/s/D_QlG0XNXKAP1HG3kizmwg"));
        items.add(new AtlasData("纽约哥伦比亚大学欧...", "https://mp.weixin.qq.com/s/z5kLqLD4aeegFiTHQ3HgKA"));
        items.add(new AtlasData("美国疾病控制与预防...", "https://www.thepaper.cn/newsDetail_forward_6961709"));
        items.add(new AtlasData("据武汉市核酸检测平...", "https://www.yicai.com/news/100594559.html"));
        items.add(new AtlasData("武汉启动了1.1万...", "https://www.yicai.com/news/100593091.html"));
        items.add(new AtlasData("印度医学研究委员会...", "https://www.thepaper.cn/newsDetail_forward_6999109"));
        items.add(new AtlasData("山东大学王培会教授...", "https://mp.weixin.qq.com/s/YWjXXg7ODi1mz-XPIoxIyA"));
        items.add(new AtlasData("美国纽约西奈山伊坎...", "https://mp.weixin.qq.com/s/649PpLBk0VTjGYlLrkULIQ"));
        items.add(new AtlasData("荷兰鹿特丹伊拉斯姆...", "https://mp.weixin.qq.com/s/ZzPu7GAC6b_ra5a6xlTFng"));
        items.add(new AtlasData("美国国立卫生研究院...", "http://news.sciencenet.cn/htmlnews/2020/4/438575.shtm"));
        items.add(new AtlasData("美国国立卫生研究院...", "http://www.sci666.com.cn/49645.html"));
        items.add(new AtlasData("欧美科研人员近期发...", "https://www.thepaper.cn/newsDetail_forward_7057228"));
        items.add(new AtlasData("牛津大学研究人员德...", "http://science.caixin.com/2020-04-20/101544614.html"));
        items.add(new AtlasData("荷兰鹿特丹伊拉斯姆...", "http://science.caixin.com/2020-04-20/101544927.html"));
        items.add(new AtlasData("中山大学附属第六医...", "https://www.thepaper.cn/newsDetail_forward_7068020"));
        items.add(new AtlasData("美国德克萨斯大学奥...", "https://mp.weixin.qq.com/s/rGsJYe5uEk4k38DyBK5Wsw"));
        items.add(new AtlasData("美国国土安全部官员...", "https://www.thepaper.cn/newsDetail_forward_7117038"));
        items.add(new AtlasData("美国纽约一医院的多...", "https://www.thepaper.cn/newsDetail_forward_7101293"));
        items.add(new AtlasData("美国疾病控制和预防...", "http://news.sciencenet.cn/htmlnews/2020/4/438810.shtm"));
        items.add(new AtlasData("浙江大学医学部梁廷...", "http://news.sciencenet.cn/htmlnews/2020/4/438780.shtm"));
        items.add(new AtlasData("浙江大学梁廷波团队...", "https://mp.weixin.qq.com/s/6TDLONBNmYl6C6Ub6LMeYg"));
        items.add(new AtlasData("哈佛医学院研究人员...", "https://mp.weixin.qq.com/s/exJTA2ja42UlaseRnI7aIA"));
        items.add(new AtlasData("浙江大学医学院研究...", "https://mp.weixin.qq.com/s/r6nl57m7tU_LphuSldPX0w"));
        items.add(new AtlasData("英国维康桑格研究所...", "http://www.sci666.com.cn/50606.html"));
        items.add(new AtlasData("世界卫生组织指出感...", "https://www.yicai.com/news/100611406.html"));
        items.add(new AtlasData("陆军军医大学研究人...", "https://mp.weixin.qq.com/s/X7b9-nD2Tj80h41dOvXVhA"));
        items.add(new AtlasData("复旦大学公共卫生学...", "https://mp.weixin.qq.com/s/izN0PY5TRqBlojhr_cwDWg"));
        items.add(new AtlasData("法国研究人员收集了...", "https://www.thepaper.cn/newsDetail_forward_7210999"));
        items.add(new AtlasData("新加坡国立大学苏瑞...", "http://news.sciencenet.cn/htmlnews/2020/5/439279.shtm"));
        items.add(new AtlasData("美国耶鲁大学研究人...", "https://baijiahao.baidu.com/s?id=1665554797695255489&wfr=spider&for=pc"));
        items.add(new AtlasData("中外研究团队研究人...", "http://science.caixin.com/2020-05-01/101549555.html"));
        items.add(new AtlasData("复旦大学公共卫生学...", "http://news.sciencenet.cn/htmlnews/2020/5/439222.shtm"));
        items.add(new AtlasData("约翰·霍普金斯大学...", "https://mp.weixin.qq.com/s/5r1DnyvPelWuStpoNJETfg"));
        items.add(new AtlasData("重庆医科大学研究人...", "https://mp.weixin.qq.com/s/9ZARrZFeLEeTNsc8EsBXvA"));
        items.add(new AtlasData("法国日前发现该国最...", "https://www.yicai.com/news/100617054.html"));
        items.add(new AtlasData("陆军军医大学卞修教...", "https://news.dayoo.com/society/202005/02/140000_53323214.htm"));
        items.add(new AtlasData("中山大学公共卫生学...", "http://news.huaxi100.com/index.php?a=show&c=index&catid=18&id=1037960&m=content"));
        items.add(new AtlasData("加拿大英属哥伦比亚...", "https://mp.weixin.qq.com/s/8R044XDSKsvmCEUFnZydlA"));
        items.add(new AtlasData("中国研究人员在感染...", "https://www.thepaper.cn/newsDetail_forward_7304421"));
        items.add(new AtlasData("香港大学研究人员研...", "http://science.caixin.com/2020-05-08/101551800.html"));
        items.add(new AtlasData("美国约翰斯·霍普金...", "http://news.medlive.cn/all/info-progress/show-168889_60.html"));
        items.add(new AtlasData("智利研究人员研究发...", "http://news.sina.com.cn/w/2020-05-12/doc-iirczymk1230650.shtml"));
        items.add(new AtlasData("世卫组织工作人员称...", "https://www.thepaper.cn/newsDetail_forward_7358958"));
        items.add(new AtlasData("意大利研究人员评估...", "http://news.bioon.com/article/6755735.html"));
        items.add(new AtlasData("多伦多大学研究人员...", "https://www.thepaper.cn/newsDetail_forward_7375415"));
        items.add(new AtlasData("意大利研究人员研究...", "https://mp.weixin.qq.com/s/q-hIz7IUH0yQDybncrodIg"));
        items.add(new AtlasData("国外研究人员研究发...", "https://mp.weixin.qq.com/s/4K2NgB_hL5XvYGUfoP-O6A"));
        items.add(new AtlasData("美国NIH研究人员...", "https://mp.weixin.qq.com/s/_kG5zvD0cnpeujfhRvMwAw"));
        items.add(new AtlasData("深圳市第三人民医院...", "https://mp.weixin.qq.com/s/UIkWEYnxmFTVxIbJD4hHsA"));
        items.add(new AtlasData("以色列雷霍沃特魏茨...", "http://news.bioon.com/article/6755716.html"));
        items.add(new AtlasData("意大利研究人员研究...", "http://news.sciencenet.cn/htmlnews/2020/5/439730.shtm"));
        items.add(new AtlasData("香港大学研究人员研...", "https://mp.weixin.qq.com/s/dMkeqVH2FxOCkVM3OWruGQ"));
        items.add(new AtlasData("香港大学研究人员发...", "https://mp.weixin.qq.com/s/dMkeqVH2FxOCkVM3OWruGQ"));
        items.add(new AtlasData("香港大学袁国勇团队...", "https://mp.weixin.qq.com/s/vDgp4icGFmSy8U6KKwjBfw"));
        items.add(new AtlasData("美国拉霍亚过敏和免...", "https://mp.weixin.qq.com/s/JnJ94zQ5burSlnvL-YKyhA"));
        items.add(new AtlasData("香港大学李嘉诚医学...", "http://www.caixin.com/2020-05-15/101554646.html"));
        items.add(new AtlasData("冷泉港实验室研究人...", "https://mp.weixin.qq.com/s/i9v99F0I7EuVHkw-3_vyzA"));
        items.add(new AtlasData("美国普林斯顿大学研...", "https://mp.weixin.qq.com/s/zjiGqADhlCWO2mJT_COSRw"));
        items.add(new AtlasData("哈佛公共卫生学院研...", "https://www.thepaper.cn/newsDetail_forward_7460164"));
        items.add(new AtlasData("英国《自然·医学》...", "https://www.thepaper.cn/newsDetail_forward_7474756"));
        items.add(new AtlasData("哈佛医学院研究人员...", "https://mp.weixin.qq.com/s/6RSo_XBsyO0MDi0twzzfrA"));
        items.add(new AtlasData("美国研究人员的两项...", "https://www.thepaper.cn/newsDetail_forward_7491255"));
        items.add(new AtlasData("纽约西奈山伊坎医学...", "https://mp.weixin.qq.com/s/L-9_swEPsGEjDwFtoHOipw"));
        items = new ArrayList<>();
        atlasItems.add(items);
        items.add(new AtlasData("武大中南医院研究人...", "https://mp.weixin.qq.com/s/gXGs3-lKMJ8IL6fIY8f6eQ"));
        items.add(new AtlasData("深圳市第三人民医院...", "https://mp.weixin.qq.com/s/2eBmS-I6E2MhYZaej__68Q"));
        items.add(new AtlasData("北京大学第一医院感...", "http://www.bast.net.cn/art/2020/3/25/art_24063_454194.html?from=timeline"));
        items.add(new AtlasData("香港大学研究团队发...", "http://sa.sogou.com/sgsearch/sgs_tc_news.php?req=RKLNg6Ri5c3GIICnws8_PZ2RJGlMDr8OpdA5WeblfRY=&f_type=feed&mat=0"));
        items.add(new AtlasData("空军军医大学陈志南...", "https://mp.weixin.qq.com/s/8u6G_W6OgotFBTxFkh-odA"));
        items.add(new AtlasData("广州医科大学附属广...", "http://news.sciencenet.cn/htmlnews/2020/3/437417.shtm"));
        items.add(new AtlasData("郑州大学王宇明团队...", "https://mp.weixin.qq.com/s/XA4dacxJaz6TvvBot2qGdA"));
        items.add(new AtlasData("Angus Cam...", "https://mp.weixin.qq.com/s/Pz1nGh6BvzV7VkckzFldmw"));
        items.add(new AtlasData("华盛顿大学研究团队...", "https://mp.weixin.qq.com/s/h9DPqbC_8MLQzeq-6HFYUQ"));
        items.add(new AtlasData("Didier Ra...", "https://mp.weixin.qq.com/s/7QfrYAI2Ga7M9jJb4Scm1Q"));
        items.add(new AtlasData("中日友好医院副院长...", "http://www.caixin.com/2020-03-19/101531212.html"));
        items.add(new AtlasData("中日医院呼吸与危重...", "https://baijiahao.baidu.com/s?id=1661559736117067054&wfr=spider&for=pc"));
        items.add(new AtlasData("中国工程院院士王辰...", "http://news.sina.com.cn/c/2020-03-19/doc-iimxxsth0169184.shtml"));
        items.add(new AtlasData("兰州大学公共卫生学...", "https://mp.weixin.qq.com/s/f5vnRrMH0uc-YkQqgARE6Q"));
        items.add(new AtlasData("南方科技大学8家单...", "https://view.inews.qq.com/k/20200317A0SZR500?openid=o04IBAOgPA9j-qhuvbLoSS3-dfwA&key=&version=27000c36&devicetype=android-29&wuid=oDdoCt87z_gbnJOautmLj-5Pew_g&sharer=o04IBAOgPA9j-qhuvbLoSS3-dfwA&uid=&shareto="));
        items.add(new AtlasData("等机构研究人员发现...", "https://mp.weixin.qq.com/s/2PuyqX1q7V6L_oCjEhcezA"));
        items.add(new AtlasData("美国心脏病学会（A...", "https://www.linkresearcher.com/information/05895008-752c-4a3b-8d19-8266ba9b1372"));
        items.add(new AtlasData("北京解放军总医院第...", "http://www.sci666.com.cn/43732.html"));
        items.add(new AtlasData("北京大学团队与美国...", "http://news.sciencenet.cn/htmlnews/2020/3/436882.shtm"));
        items.add(new AtlasData("中日友好医院曹彬和...", "http://www.sci666.com.cn/43214.html"));
        items.add(new AtlasData("新冠肺炎患者不仅有...", "http://www.sci666.com.cn/42814.html"));
        items.add(new AtlasData("仅旅行限制并不能有...", "http://www.sci666.com.cn/41931.html"));
        items.add(new AtlasData("数字模型显示国外疫...", "http://www.sci666.com.cn/41791.html"));
        items.add(new AtlasData("首都医科大学附属北...", "http://www.sci666.com.cn/41791.html"));
        items.add(new AtlasData("武汉协和医院西院区...", "https://www.takefoto.cn/viewnews-2072346.html"));
        items.add(new AtlasData("新冠病毒对神经系统...", "https://www.sohu.com/a/377690300_313745"));
        items.add(new AtlasData("钟南山团队最新成果...", "https://view.inews.qq.com/k/20200302A07C8Q00?openid=o04IBAPFjq2kQPu26if6Ewu7AskU&key=&version=27000b33&devicetype=android-28&wuid=oDdoCt1a3_NE85GbG0gXgYCDsLJc&sharer=o04IBAPFjq2kQPu26if6Ewu7AskU&uid=&shareto="));
        items.add(new AtlasData("世卫组织指出，对于...", "https://view.inews.qq.com/k/20200302A08FFB00?openid=o04IBAPFjq2kQPu26if6Ewu7AskU&key=&version=27000b33&devicetype=android-28&wuid=oDdoCt1a3_NE85GbG0gXgYCDsLJc&sharer=o04IBAPFjq2kQPu26if6Ewu7AskU&uid=&shareto="));
        items.add(new AtlasData("新冠病毒或对神经系...", "http://china.caixin.com/2020-02-27/101521348.html"));
        items.add(new AtlasData("官方通报的首例不明...", "http://www.mnw.cn/news/shehui/2244308.html"));
        items.add(new AtlasData("美国疾病控制与预防...", "https://t.qianzhan.com/caijing/detail/200401-4ad95dae.html"));
        items.add(new AtlasData("深圳市第三人民医院...", "https://mp.weixin.qq.com/s/mhBbSnLSyzcDWTM58Sj7UA"));
        items.add(new AtlasData("武汉大学张旃团队研...", "https://mp.weixin.qq.com/s/mtZNG4HuyytVObbpmDvx-w"));
        items.add(new AtlasData("深圳第三人民医院研...", "http://www.sci666.com.cn/46782.html"));
        items.add(new AtlasData("钟南山院士团队研究...", "http://sa.sogou.com/sgsearch/sgs_tc_news.php?req=l6yV8pIlpck3dDDXwZOwZYCt8RpnvBmyRFVX-iTq3Uo=&f_type=feed"));
        items.add(new AtlasData("武汉大学人民医院的...", "https://mp.weixin.qq.com/s/SV8H1KwsfqLQ5VIRwxkVGQ"));
        items.add(new AtlasData("日前，中国科学院院...", "https://tech.sina.com.cn/d/2020-04-01/doc-iimxyqwa4388613.shtml"));
        items.add(new AtlasData("曹彬等人发论文：克...", "https://avatarcdn.aminer.cn/upload/avatar/167/1072/403/542d579fdabfae11fc45fd96.jpeg!160"));
        items.add(new AtlasData("武汉8家机构研究发...", "https://www.tmtpost.com/nictation/4274312.html"));
        items.add(new AtlasData("曹彬团队分析首批新...", "https://tech.sina.com.cn/d/2020-03-11/doc-iimxxstf8084131.shtml"));
        items.add(new AtlasData("曹彬《柳叶刀》论文...", "http://news.sina.com.cn/c/2020-03-10/doc-iimxyqvz9390941.shtml"));
        items.add(new AtlasData("山东潍坊卫恩医院院...", "http://news.sciencenet.cn/htmlnews/2020/4/437919.shtm"));
        items.add(new AtlasData("中国工程院院士仝小...", "http://news.cnwest.com/tianxia/a/2020/03/31/18621775.html"));
        items.add(new AtlasData("国药集团中国生物研...", "http://news.sciencenet.cn/htmlnews/2020/4/438060.shtm"));
        items.add(new AtlasData("中国一个研究团队研...", "https://mp.weixin.qq.com/s/4V0g6LpgeecFjQtHPZa8Ag"));
        items.add(new AtlasData("博德研究所张锋团队...", "https://mp.weixin.qq.com/s/qadTYRGgv1MyBPWtGsLKQg"));
        items.add(new AtlasData("华中科技大学公共卫...", "https://mp.weixin.qq.com/s/U7hZWgRBBmt9nBSE7J21Zg"));
        items.add(new AtlasData("钟南山院士团队的科...", "http://news.sciencenet.cn/htmlnews/2020/4/438162.shtm"));
        items.add(new AtlasData("上海公共卫生临床研...", "https://www.yicai.com/news/100588912.html"));
        items.add(new AtlasData("巴西研究团队研究发...", "https://mp.weixin.qq.com/s/jiwEzK3WXsqvSMqlVydUSA"));
        items.add(new AtlasData("华中科技大学同济医...", "https://www.thepaper.cn/newsDetail_forward_6962254"));
        items.add(new AtlasData("四川大学华西医院研...", "https://mp.weixin.qq.com/s/yIBult3CXKb7iNWOi2vgjw"));
        items.add(new AtlasData("上海中医药大学附属...", "https://www.thepaper.cn/newsDetail_forward_7016059"));
        items.add(new AtlasData("中国多地医务工作者...", "https://www.thepaper.cn/newsDetail_forward_6997541"));
        items.add(new AtlasData("北海道大学教授西浦...", "https://www.thepaper.cn/newsDetail_forward_6996286"));
        items.add(new AtlasData("深圳第三人民医院陈...", "https://mp.weixin.qq.com/s/2aZU0W2CVruQ6OFBrtrqLg"));
        items.add(new AtlasData("福建医科大学研究人...", "https://mp.weixin.qq.com/s/SRlpeNqlBMT0X_WyY-RFyA"));
        items.add(new AtlasData("广州医科大学李时悦...", "https://mp.weixin.qq.com/s/eud3K06DKJBwDps2DRBs_w"));
        items.add(new AtlasData("中日友好医院副院长...", "http://www.caixin.com/2020-04-19/101544435.html"));
        items.add(new AtlasData("北京大学第三医院乔...", "http://news.sciencenet.cn/htmlnews/2020/4/438579.shtm"));
        items.add(new AtlasData("浙江大学王福俤教授...", "https://mp.weixin.qq.com/s/LVXNJCTqT4KgBrO5wXJBJw"));
        items.add(new AtlasData("梅雷迪思-瓦德曼总...", "https://mp.weixin.qq.com/s/lKEz0svchnFCSRp5asP2BQ"));
        items.add(new AtlasData("苏州大学附属第一医...", "https://mp.weixin.qq.com/s/OVEN1c8fsZaQA0MtoR698g?from=singlemessage&isappinstalled=0&scene=1&clicktime=1587728817&enterid=1587728817"));
        items.add(new AtlasData("德国马丁路德·哈勒...", "https://mp.weixin.qq.com/s/PE0xCp4jPoZ_Plu0nDMUvA"));
        items.add(new AtlasData("华中科技大学同济医...", "https://mp.weixin.qq.com/s/AXnqm_284oqN2D9yUf7mYg"));
        items.add(new AtlasData("东部战区总医院生殖...", "http://www.caixin.com/2020-04-24/101546687.html"));
        items.add(new AtlasData("浙江大学研究人员研...", "http://www.caixin.com/2020-04-22/101545632.html"));
        items.add(new AtlasData("南卡罗来纳大学研究...", "https://mp.weixin.qq.com/s/4ClwWIcTkfeTEi9IL4svQA"));
        items.add(new AtlasData("武汉大学李红良教授...", "https://mp.weixin.qq.com/s/g_hpvUuJfUwlYkEpQP_21g"));
        items.add(new AtlasData("美国弗吉尼亚大学等...", "https://mp.weixin.qq.com/s/a5x9hkTk9pWaKa3wUpOIsg"));
        items.add(new AtlasData("澳门科技大学等机构...", "https://mp.weixin.qq.com/s/mQ5FSEaxWbmxNcsvfLgpcw"));
        items.add(new AtlasData("南京医科大学第一附...", "http://news.sciencenet.cn/htmlnews/2020/4/438924.shtm"));
        items.add(new AtlasData("华中科技大学同济医...", "https://mp.weixin.qq.com/s/3zIpHZ6aEM01DdBUMGbsvA"));
        items.add(new AtlasData("武汉大研究人员对武...", "http://news.sciencenet.cn/htmlnews/2020/4/439077.shtm"));
        items.add(new AtlasData("中科院武汉病毒所研...", "https://mp.weixin.qq.com/s/k0-xD-5s3RuHvMYwWoAP7A"));
        items.add(new AtlasData("北京首都医科大学附...", "https://mp.weixin.qq.com/s/OYH_kfHIkw7sDZXFs-b4Cw"));
        items.add(new AtlasData("曹彬团队研究发现重...", "https://www.deepl.com/translator#zh/en/%E6%9B%B9%E5%BD%AC%E5%9B%A2%E9%98%9F%E7%A0%94%E7%A9%B6%E5%8F%91%E7%8E%B0%E9%87%8D%E7%97%87%E6%96%B0%E5%86%A0%E6%82%A3%E8%80%85%E7%9A%84%E4%B8%B4%E5%BA%8A%E8%A1%A8%E7%8E%B0%E7%AC%A6%E5%90%88%E8%84%93%E6%AF%92%E7%97%87%E6%88%96%E8%84%93%E6%AF%92%E7%97%87%E4%BC%91%E5%85%8B%E7%9A%84%E8%AF%8A%E6%96%AD%E6%A0%87%E5%87%86%EF%BC%8C%E4%BA%8C%E8%80%85%E8%87%B4%E7%97%85%E6%9C%BA%E7%90%86%E4%B9%9F%E6%9C%89%E7%9B%B8%E4%BC%BC%E4%B9%8B%E5%A4%84%EF%BC%8C%E7%97%85%E6%AF%92%E6%80%A7%E8%84%93%E6%AF%92%E7%97%87%E6%88%96%E4%B8%BA%E6%96%B0%E5%86%A0%E8%82%BA%E7%82%8E%E7%9A%84%E5%85%B3%E9%94%AE%E8%87%B4%E7%97%85%E6%9C%BA%E5%88%B6%E4%B9%8B%E4%B8%80%EF%BC%8C%E4%BD%86%E8%BF%99%E4%B8%80%E5%81%87%E8%AF%B4%E7%9B%AE%E5%89%8D%E5%B0%9A%E4%B8%8D%E5%AE%8C%E5%96%84%E3%80%82"));
        items.add(new AtlasData("武汉大学研究人员研...", "https://mp.weixin.qq.com/s/TskCt1kisEeAklYMZi-iJA"));
        items.add(new AtlasData("法国研究人员重新检...", "https://mp.weixin.qq.com/s/OZEAtLsp3X2kdxRe7T3S_A"));
        items.add(new AtlasData("王辰、曹彬等在NE...", "https://mp.weixin.qq.com/s/7taYyyRbWP2lwwckypKT1w"));
        items.add(new AtlasData("医学期刊《柳叶刀》...", "http://www.caixin.com/2020-05-11/101552479.html"));
        items.add(new AtlasData("北京协和医院研究人...", "https://mp.weixin.qq.com/s/aVoHxVmB8VrzHTGs_SuzxQ"));
        items.add(new AtlasData("美国研究人员发现糖...", "http://news.bioon.com/article/6755734.html"));
        items.add(new AtlasData("伦敦大学学院进行的...", "https://mp.weixin.qq.com/s/eqDJOL422yD5hK3Bn5bZNw"));
        items.add(new AtlasData("以色列生物公司St...", "https://www.jinse.com/news/blockchain/669686.html"));
        items.add(new AtlasData("科罗拉多大学研究人...", "https://new.qq.com/omn/20200513/20200513A0JMBF00.html"));
        items.add(new AtlasData("上海交大附属瑞金医...", "https://www.yicai.com/news/100630976.html"));
        items.add(new AtlasData("华中科技大学同济医...", "http://news.sciencenet.cn/htmlnews/2020/5/439826.shtm"));
        items.add(new AtlasData("武汉大学人民医院黄...", "http://news.sina.com.cn/o/2020-05-19/doc-iirczymk2463915.shtml"));
        items.add(new AtlasData("英国国民医疗服务体...", "https://www.thepaper.cn/newsDetail_forward_7492413"));
        items = new ArrayList<>();
        atlasItems.add(items);
        items.add(new AtlasData("美国制药企业吉利德...", "http://www.caixin.com/2020-03-26/101534156.html"));
        items.add(new AtlasData("东京大学已确认甲磺...", "https://finance.sina.cn/stock/relnews/dongmiqa/2020-03-25/detail-iimxxsth1639324.d.html"));
        items.add(new AtlasData("美国食品和药品管理...", "https://www.yicai.com/news/100562332.html"));
        items.add(new AtlasData("钟南山团队的新筛查...", "https://news.sina.com.cn/c/2020-03-11/doc-iimxyqvz9555976.shtml"));
        items.add(new AtlasData("Fauci、Lan...", "https://2019-ncov.aminer.cn/details?id=5448a76fdabfae87b7e5ac64"));
        items.add(new AtlasData("新冠肺炎药物具有临...", "https://www.yicai.com/news/100523940.html"));
        items.add(new AtlasData("美国吉利德科学宣布...", "https://www.yicai.com/news/100524372.html"));
        items.add(new AtlasData("美国启动首个瑞德西...", "https://www.linkresearcher.com/information/9d1c6506-41a8-4d91-9e73-da46c01e6735"));
        items.add(new AtlasData("抗病毒药物瑞德西韦...", "https://new.qq.com/zt/template/?id=TWF2020020600206600&pgv_ref=aio2015&ptlang=2052"));
        items.add(new AtlasData("吉利德瑞德西韦，该...", "https://www.antpedia.com/index.php?action-viewnews-itemid-2355590-php-1"));
        items.add(new AtlasData("袁正宏/应天雷团队...", "https://news.fudan.edu.cn/2019/1204/c1357a103355/page.htm"));
        items.add(new AtlasData("英国圣玛丽医院研究...", "http://www.sci666.com.cn/47615.html"));
        items.add(new AtlasData("期刊IJAA发布公...", "http://www.sci666.com.cn/47794.html"));
        items.add(new AtlasData("吉利德科学（Gil...", "https://www.yicai.com/news/100585771.html"));
        items.add(new AtlasData("德国联邦药品与医疗...", "https://www.yicai.com/news/100585771.html"));
        items.add(new AtlasData("《新英格兰医学杂志...", "http://news.sciencenet.cn/htmlnews/2020/4/438219.shtm"));
        items.add(new AtlasData("临床试验注册网站c...", "http://www.sci666.com.cn/49224.html"));
        items.add(new AtlasData("Incyte宣布启...", "https://mp.weixin.qq.com/s/AZsj1d0feXmlOvv60BuzpQ"));
        items.add(new AtlasData("Alexion制药...", "https://mp.weixin.qq.com/s/ba0KvcdjUy1lY2zt6xZOlA"));
        items.add(new AtlasData("深圳市妇幼保健院和...", "https://mp.weixin.qq.com/s/uWCzlCclJuRNVsqTJrO9BA"));
        items.add(new AtlasData("深圳市妇幼保健院的...", "http://www.sci666.com.cn/50688.html"));
        items.add(new AtlasData("曹彬教授牵头进行的...", "http://www.sci666.com.cn/50688.html"));
        items.add(new AtlasData("中国进行的瑞德西韦...", "http://news.sciencenet.cn/htmlnews/2020/4/439156.shtm"));
        items.add(new AtlasData("约翰霍普金斯大学医...", "https://mp.weixin.qq.com/s/nbosCNlVdCM7rbE74GpIQw"));
        items.add(new AtlasData("中日友好医院曹彬教...", "http://finance.eastmoney.com/a/202004111451177563.html"));
        items.add(new AtlasData("瑞德西韦在日本以外...", "https://www.yicai.com/news/100621483.html"));
        items = new ArrayList<>();
        atlasItems.add(items);
        items.add(new AtlasData("军事科学院军事医学...", ""));
        items.add(new AtlasData("广州医科大学研究人...", "https://mp.weixin.qq.com/s/vUKuVzY6vQ0AE1ch_k2OCQ"));
        items.add(new AtlasData("武汉大学张蔚团队在...", "https://mp.weixin.qq.com/s/pqugeoJJQQHbjG38TDyR_A"));
        items.add(new AtlasData("科亚医疗采用深度学...", "https://tech.sina.com.cn/roll/2020-03-20/doc-iimxxsth0494562.shtml"));
        items.add(new AtlasData("武汉大学官网3月1...", "https://mbd.baidu.com/newspage/data/landingshare?pageType=1&isBdboxFrom=1&context=%7B%22nid%22%3A%22news_9452247927634041994%22%2C%22sourceFrom%22%3A%22bjh%22%7D"));
        items.add(new AtlasData("中央指导组专家组成...", "http://politics.gmw.cn/2020-03/18/content_33660765.htm"));
        items.add(new AtlasData("中国科技大学魏海明...", "https://mp.weixin.qq.com/s/wwUGMfGGXesi_muiVfwEJQ"));
        items.add(new AtlasData("清华大学曾坚阳、朱...", "http://www.sci666.com.cn/43796.html"));
        items.add(new AtlasData("面对全球的大流行...", "http://www.hubeitoday.com.cn/post/5/119997"));
        items.add(new AtlasData("由中国工程院院士钟...", "https://www.yicai.com/news/100545711.html"));
        items.add(new AtlasData("托珠单抗（Toci...", "http://www.sci666.com.cn/41791.html"));
        items.add(new AtlasData("天津医科大学附属肿...", "http://www.sci666.com.cn/38374.html"));
        items.add(new AtlasData("上海专家团队探索新...", "https://m.yicai.com/news/100510557.html"));
        items.add(new AtlasData("中医药有效方剂筛选...", "http://bgs.satcm.gov.cn/gongzuodongtai/2020-02-06/12866.html"));
        items.add(new AtlasData("中科院李兰娟团队在...", "https://tech.sina.cn/2020-02-04/detail-iimxxste8805438.d.html?vt=4&pos=18"));
        items.add(new AtlasData("李兰娟团队推荐药物...", "https://mp.weixin.qq.com/s/aGM4FE3AK70ZE-w6Jn-3Hg"));
        items.add(new AtlasData("国家卫健委高级别专...", "http://www.sohu.com/a/363899297_100207663"));
        items.add(new AtlasData("国务院、国家卫健委...", "https://mp.weixin.qq.com/s/4KORE8f7rCfzXmHZ6VCJtQ"));
        items.add(new AtlasData("清华大学张林琦教授...", "https://mp.weixin.qq.com/s/cIy-kkXYHirhQK96VduA0g"));
        items.add(new AtlasData("中医药使用率达83...", "http://finance.eastmoney.com/a/202002181388052071.html"));
        items.add(new AtlasData("中...", "https://avatarcdn.aminer.cn/upload/avatar/1277/2016/1952/542cd86edabfae4bbcf7ce63.jpeg!160"));
        items.add(new AtlasData("《干细胞治疗新型冠...", "http://news.bioon.com/article/6753007.html"));
        items.add(new AtlasData("为进一步提升干细胞...", "https://www.thepaper.cn/newsDetail_forward_6609081"));
        items.add(new AtlasData("中国工程院李兰娟院...", "https://mp.weixin.qq.com/s/RNKoTgAWEP6MCFKRSlI1yA"));
        items.add(new AtlasData("中国工程院院士乔杰...", "http://news.sciencenet.cn/htmlnews/2020/4/437871.shtm"));
        items.add(new AtlasData("中国工程院院士王辰...", "http://news.sciencenet.cn/htmlnews/2020/4/437898.shtm"));
        items.add(new AtlasData("中国科学院外籍院士...", "http://news.sciencenet.cn/htmlnews/2020/4/437983.shtm"));
        items.add(new AtlasData("清华大学和杜克-新...", "http://www.caixin.com/2020-04-09/101540277.html"));
        items.add(new AtlasData("中科院苏州医工所汪...", "http://news.sciencenet.cn/htmlnews/2020/4/438132.shtm"));
        items.add(new AtlasData("数坤(北京)网络科...", "http://www.beijing.gov.cn/ywdt/zwzt/yqfk/bjfk/t1625263.htm"));
        items.add(new AtlasData("中国工程院院士曹雪...", "http://news.sciencenet.cn/htmlnews/2020/4/438248.shtm"));
        items.add(new AtlasData("武汉大学李红良等人...", "https://mp.weixin.qq.com/s/998eY1DgIClUG26OnJ9Lzw"));
        items.add(new AtlasData("中国临床治疗新技术...", "https://www.thepaper.cn/newsDetail_forward_6962736"));
        items.add(new AtlasData("华中科技大学同济医...", "http://news.sciencenet.cn/htmlnews/2020/4/438429.shtm"));
        items.add(new AtlasData("英国国家医疗服务体...", "https://www.thepaper.cn/newsDetail_forward_7055871"));
        items.add(new AtlasData("中国医学科学院秦川...", "https://mp.weixin.qq.com/s/S1ICp7hBJUaID63mW11ccw"));
        items.add(new AtlasData("中国工程院院士钟南...", "http://news.sciencenet.cn/htmlnews/2020/4/438764.shtm"));
        items.add(new AtlasData("由中科普瑞昇公司和...", "http://news.sciencenet.cn/htmlnews/2020/4/439011.shtm"));
        items.add(new AtlasData("西湖大学研究人员构...", "https://mp.weixin.qq.com/s/F23okZ270QhZVs5FcEaJgQ"));
        items.add(new AtlasData("西湖大学研究人员肠...", "https://www.thepaper.cn/newsDetail_forward_7181187"));
        items.add(new AtlasData("比利时研究人员研究...", "https://www.thepaper.cn/newsDetail_forward_7242299"));
        items.add(new AtlasData("中国工程院院士张伯...", "https://www.takefoto.cn/viewnews-2126363.html"));
        items.add(new AtlasData("清华大学饶子和院士...", "https://www.instrument.com.cn/news/20200501/536770.shtml"));
        items.add(new AtlasData("中国工程院院士王辰...", "https://tech.ifeng.com/c/7vsLMqk2JNr"));
        items.add(new AtlasData("李兰娟院士表示在在...", "https://news.china.com/socialgd/10000169/20200420/38105933_all.html"));
        items.add(new AtlasData("中国工程院院士黄璐...", "http://news.sina.com.cn/c/2020-04-18/doc-iircuyvh8561340.shtml"));
        items.add(new AtlasData("中国工程院院士乔杰...", "https://www.thepaper.cn/newsDetail_forward_7028385"));
        items.add(new AtlasData("由中华中医药学会和...", "https://www.thepaper.cn/newsDetail_forward_7039915"));
        items.add(new AtlasData("中国科学院院士王福...", "http://news.cnwest.com/tianxia/a/2020/04/11/18651448.html"));
        items.add(new AtlasData("军事医学科学院生物...", "https://mp.weixin.qq.com/s/s6FfhSEC4dCEoSuMpf9_6A"));
        items.add(new AtlasData("清华大学研究人员从...", "https://mp.weixin.qq.com/s/q5YY0q2Sv7Gt1w44cQYFmg"));
        items.add(new AtlasData("意大利药理学者安娜...", "http://news.sciencenet.cn/htmlnews/2020/5/439312.shtm"));
        items.add(new AtlasData("军事科学院军事医学...", "https://mp.weixin.qq.com/s/a7X-rhziQHXGi6iVycjC-w"));
        items.add(new AtlasData("中国工程院院士钟南...", "http://news.sciencenet.cn/htmlnews/2020/5/439754.shtm"));
        items.add(new AtlasData("北京大学北京未来基...", "http://news.sciencenet.cn/htmlnews/2020/5/439920.shtm"));
        items.add(new AtlasData("法国卫生和医学研究...", "http://news.sciencenet.cn/htmlnews/2020/5/439904.shtm"));
        items.add(new AtlasData("美国洛克菲勒大学研...", "http://news.sciencenet.cn/htmlnews/2020/5/439833.shtm"));
        items.add(new AtlasData("清华大学等机构研究...", "https://www.thepaper.cn/newsDetail_forward_7458069"));
        items.add(new AtlasData("上海市公共卫生临床...", "https://www.yicai.com/news/100637346.html"));
        items = new ArrayList<>();
        atlasItems.add(items);
        items.add(new AtlasData("杜兰大学医学院罗伯...", "http://sa.sogou.com/sgsearch/sgs_tc_news.php?req=lmRH2T9uMVfe8VYFm_5n7fNirOmp7yfHd0Q43Zd-dgc=&f_type=feed&mat=0"));
        items.add(new AtlasData("deCODE基因公...", "http://sa.sogou.com/sgsearch/sgs_tc_news.php?req=3ACznnLZgZXuxb7jeTChpVqrYEbbpfPV2lhQFsSNQUQ=&f_type=feed&mat=0"));
        items.add(new AtlasData("悉尼大学生命与环境...", "http://sa.sogou.com/sgsearch/sgs_tc_news.php?req=trZbAzRpRpYUw5FCE_4UwB8rC4xoY7Mkp38PEUA-mo0=&f_type=feed&mat=0"));
        items.add(new AtlasData("哈佛大学医学院的专...", "https://www.yicai.com/news/100570128.html"));
        items.add(new AtlasData("以色列国防部表示对...", "https://tech.sina.com.cn/roll/2020-03-25/doc-iimxxsth1686267.shtml"));
        items.add(new AtlasData("Moderna或在...", "https://tech.sina.com.cn/roll/2020-03-24/doc-iimxyqwa2818370.shtml"));
        items.add(new AtlasData("德国研究人员研究发...", "http://news.sciencenet.cn/htmlnews/2020/3/437283.shtm"));
        items.add(new AtlasData("日本川崎生物数据公...", "https://mp.weixin.qq.com/s/WrJkoHHX-HDpcDp3TA1TOQ"));
        items.add(new AtlasData("随着疫情发酵和影响...", "https://baijiahao.baidu.com/s?id=1661674694167324949&wfr=spider&for=pc"));
        items.add(new AtlasData("南方医科大学公共卫...", "http://science.caixin.com/2020-03-20/101531574.html"));
        items.add(new AtlasData("斯克利普斯研究所的...", "https://tech.sina.com.cn/roll/2020-03-19/doc-iimxyqwa1598100.shtml"));
        items.add(new AtlasData("世界卫生组织推荐了...", "http://www.sci666.com.cn/44994.html"));
        items.add(new AtlasData("美国科学家们在志愿...", "http://www.sci666.com.cn/44265.html"));
        items.add(new AtlasData("美国《科学》杂志网...", "https://news.sina.com.cn/c/2020-03-11/doc-iimxyqvz9559055.shtml"));
        items.add(new AtlasData("美国西达赛奈医疗中...", "http://www.sci666.com.cn/43032.html"));
        items.add(new AtlasData("WHO正式发布了针...", "https://www.sohu.com/a/378512723_756004"));
        items.add(new AtlasData("上海交通大学系统生...", "https://www.linkresearcher.com/information/6e320c1a-1e58-4778-8d42-1ed62133bd5f"));
        items.add(new AtlasData("国家卫健委办公厅正...", "https://mp.weixin.qq.com/s/Wikq6hrnKIZl7Iumg2bq5A"));
        items.add(new AtlasData("“我国肺移植第一人...", "https://www.thepaper.cn/newsDetail_forward_6259223"));
        items.add(new AtlasData("全球多地病毒实验室...", "https://mp.weixin.qq.com/s/EsC3A1l5snb4Q-hR7qOyvw"));
        items.add(new AtlasData("上个月杭州的Asc...", "https://www.nature.com/articles/d41587-020-00003-1"));
        items.add(new AtlasData("复旦大学联合艾跃生...", "https://www.linkresearcher.com/information/08bfc6c7-803a-444d-a66e-18e87c1c8e60"));
        items.add(new AtlasData("在发现新冠病毒的“...", "https://www.linkresearcher.com/information/5bae2dc4-23d7-40e7-95f1-505c938aa547"));
        items.add(new AtlasData("美国哥伦比亚大学公...", "https://www.sohu.com/a/376083509_126864"));
        items.add(new AtlasData("Rolf Hilg...", "https://www.acs.org/content/acs/en/pressroom/presspacs/2020/acs-presspac-february-26-2020/new-compounds-thwart-multiple-viruses-including-coronavirus.html"));
        items.add(new AtlasData("国家药品监督管理局...", "https://baijiahao.baidu.com/s?id=1659378422445721560&wfr=spider&for=pc"));
        items.add(new AtlasData("瑞士学者人工合成出...", "http://www.sci666.com.cn/38409.html"));
        items.add(new AtlasData("新冠病毒关键蛋白分...", "http://www.cankaoxiaoxi.com/science/20200222/2402512.shtml"));
        items.add(new AtlasData("中科院通过全基因组...", "http://www.sci666.com.cn/38247.html"));
        items.add(new AtlasData("新冠疫苗重大突破，...", "https://science.sciencemag.org/content/early/2020/02/19/science.abb2507"));
        items.add(new AtlasData("西湖大学研究团队在...", "https://m.yicai.com/news/100512092.html"));
        items.add(new AtlasData("杰毅生物联手浙江省...", "https://m.yicai.com/news/100510118.html"));
        items.add(new AtlasData("国际病毒分类委员会...", "https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)30419-0/fulltext"));
        items.add(new AtlasData("新冠病毒首个蛋白质...", "https://www.biorxiv.org/content/10.1101/2020.02.11.944462v1"));
        items.add(new AtlasData("CRISPR基因编...", "https://www.ubigene.com/about/information/2747.html"));
        items.add(new AtlasData("世卫组织正式命名新...", "https://www.nature.com/articles/d41586-020-00154-w"));
        items.add(new AtlasData("OpenKG 发布...", "https://zhuanlan.zhihu.com/p/106884474?utm_source=wechat_session"));
        items.add(new AtlasData("国务院联防联控机制...", "http://www.gov.cn:8080/xinwen/2020-02/08/content_5476255.htm"));
        items.add(new AtlasData("有“病毒猎人”之称...", "https://m.sohu.com/a/369940943_99937407/"));
        items.add(new AtlasData("中国疾病预防控制中...", "http://china.caixin.com/2020-01-28/101508980.html"));
        items.add(new AtlasData("权威医学杂志《新英...", "https://baijiahao.baidu.com/s?id=1656791065296642713&wfr=spider&for=pc"));
        items.add(new AtlasData("国家基因组科学数据...", "https://baijiahao.baidu.com/s?id=1656473692771408738&wfr=spider&for=pc"));
        items.add(new AtlasData("北京大学，广西中医...", "http://www.sohu.com/a/368932164_649564"));
        items.add(new AtlasData("世界卫生组织正式将...", "http://guancha.gmw.cn/2020-01/20/content_33496697.htm"));
        items.add(new AtlasData("根据石正丽研究员公...", "https://baijiahao.baidu.com/s?id=1660771967219854673&wfr=spider&for=pc"));
        items.add(new AtlasData("上海市公共卫生临床...", "http://www.caixin.com/2020-01-26/101508568.html"));
        items.add(new AtlasData("清华大学结构生物学...", "http://sa.sogou.com/sgsearch/sgs_tc_news.php?req=_gndKjohKhDrIo20mx-VV679zN83L43wBllCP739USM=&f_type=feed"));
        items.add(new AtlasData("斯坦福大学开放《用...", "https://www.yidianzixun.com/article/0OyFuNId?title_sn=0&yidian_dtype=1&utk=0068n0v5&appid=yidian&ver=5.3.4.0&f=ios&s=8&impid=291132_1585334010833_2122&from=timeline&share_count=2"));
        items.add(new AtlasData("清华大学结构生物学...", "https://mp.weixin.qq.com/s/FgWwJDrXTVOXvYbmslHxww"));
        items.add(new AtlasData("64岁的南非艾滋病...", "http://www.sci666.com.cn/47112.html"));
        items.add(new AtlasData("Science:德...", "https://new.qq.com/omn/20200325/20200325A0MKEU00.html"));
        items.add(new AtlasData("病毒学专家金冬雁：...", "http://news.sina.com.cn/c/2020-03-29/doc-iimxyqwa3919658.shtml"));
        items.add(new AtlasData("新冠病毒和SARS...", "http://finance.ifeng.com/c/7v2jbCmeiHo"));
        items.add(new AtlasData("中山大学医学院院长...", "https://www.ximalaya.com/keji/16007374/249525998"));
        items.add(new AtlasData("中疾控主任高福藉《...", "https://3g.163.com/air/article_cambrian/F8VVMCIF0537A5Y9.html"));
        items.add(new AtlasData("怀疑新冠病毒潜伏数...", "https://3g.163.com/news/article_cambrian/F976POVS051480KF.html"));
        items.add(new AtlasData("乔杰团队报道人类卵...", "https://www.360kuai.com/pc/91db405d50c565a87?cota=4&kuai_so=1&tj_url=so_rec&sign=360_da20e874&refer_scene=so_3"));
        items.add(new AtlasData("柳叶刀重磅！高福/...", "https://3g.163.com/3g/article_cambrian/F71TNP0U05329KGN.html"));
        items.add(new AtlasData("冠状病毒专家、加拿...", "https://www.sohu.com/a/372983965_247813"));
        items.add(new AtlasData("复旦大学上海医学院...", "http://www.whb.cn/zhuzhan/yiliao/20200211/323099.html"));
        items.add(new AtlasData("德克萨斯大学研究团...", "https://mp.weixin.qq.com/s/qoSfEEx_2-8r3Yst6NBBGQ"));
        items.add(new AtlasData("世界卫生组织新冠肺...", "http://news.sciencenet.cn/htmlnews/2020/4/438013.shtm"));
        items.add(new AtlasData("德国哥廷根大学研究...", "https://mp.weixin.qq.com/s/2EvrMWIBBA0HsCEwxGKpFA"));
        items.add(new AtlasData("《自然》杂志官方网...", "http://news.sciencenet.cn/htmlnews/2020/4/438063.shtm"));
        items.add(new AtlasData("中国工程院院士张改...", "http://news.sciencenet.cn/htmlnews/2020/4/438017.shtm"));
        items.add(new AtlasData("爱尔兰都柏林圣三一...", "https://tech.sina.com.cn/roll/2020-04-09/doc-iircuyvh6797566.shtml"));
        items.add(new AtlasData("梅奥医学中心传染病...", "https://www.yicai.com/news/100586174.html"));
        items.add(new AtlasData("美国图兰大学(Tu...", "https://tech.sina.com.cn/d/f/2020-04-10/doc-iirczymi5549643.shtml"));
        items.add(new AtlasData("剑桥大学研究人员在...", "https://mp.weixin.qq.com/s/8LuRDKLreW9FsX2jcJmB7Q"));
        items.add(new AtlasData("英美科学家携手制作...", "http://news.sciencenet.cn/htmlnews/2020/4/438290.shtm"));
        items.add(new AtlasData("一个由全球120多...", "https://www.yicai.com/news/100591747.html"));
        items.add(new AtlasData("芬兰阿尔托大学研究...", "https://www.thepaper.cn/newsDetail_forward_6977218"));
        items.add(new AtlasData("中国工程院院士李兰...", "https://mp.weixin.qq.com/s/fjaPEx-F1XTqxzZs3UC2Vw"));
        items.add(new AtlasData("世界卫生组织发言人...", "http://news.sciencenet.cn/htmlnews/2020/4/438828.shtm"));
        items.add(new AtlasData("世界卫生组织表示尚...", "http://news.sciencenet.cn/htmlnews/2020/4/438966.shtm"));
        items.add(new AtlasData("英国与国际伙伴包括...", "https://www.yicai.com/news/100608687.html"));
        items.add(new AtlasData("沙特政府和中国企业...", "https://www.yicai.com/news/100609691.html"));
        items.add(new AtlasData("腾讯医典携手中国国...", "https://baijiahao.baidu.com/s?id=1665186482136298437&wfr=spider&for=pc"));
        items.add(new AtlasData("英国伦敦国王学院双...", "https://mp.weixin.qq.com/s/u3hcbB_4vSI18TXqzy8p5Q"));
        items.add(new AtlasData("钟南山团队成员周荣...", "https://3g.163.com/news/article_cambrian/FAQOUMT40514B50R.html"));
        items.add(new AtlasData("金冬雁在科学公益组...", "https://www.thepaper.cn/newsDetail_forward_6896539"));
        items.add(new AtlasData("瑞士、德国、俄罗斯...", "http://news.sciencenet.cn/htmlnews/2020/5/439355.shtm"));
        items.add(new AtlasData("伦敦大学学院基因研...", "https://www.yicai.com/news/100618431.html"));
        items.add(new AtlasData("美国洛斯阿拉莫斯国...", "https://www.thepaper.cn/newsDetail_forward_7276806"));
        items.add(new AtlasData("美国康奈尔大学的生...", "https://www.thepaper.cn/newsDetail_forward_7280732"));
        items.add(new AtlasData("英国班戈大学研究团...", "https://www.thepaper.cn/newsDetail_forward_7282534"));
        items.add(new AtlasData("伦敦大学学院科学家...", "http://news.sciencenet.cn/htmlnews/2020/5/439407.shtm"));
        items.add(new AtlasData("中国医学科学院医学...", "http://news.sciencenet.cn/htmlnews/2020/5/439395.shtm"));
        items.add(new AtlasData("日本筑波大学医学研...", "https://mp.weixin.qq.com/s/s1QBWQF8TZNKEkgErelkoA"));
        items.add(new AtlasData("北京大学生命科学学...", "https://www.thepaper.cn/newsDetail_forward_7348867"));
        items.add(new AtlasData("西安大略大学等机构...", "http://news.bioon.com/article/6755615.html"));
        items.add(new AtlasData("上海交通大学医学院...", "https://mp.weixin.qq.com/s/oqiqHVANNRLEvd08kfvuJg"));
        items.add(new AtlasData("荷兰格罗宁根大学医...", "https://mp.weixin.qq.com/s/f-24zya_j-osaZbZUgNLGw"));
        items.add(new AtlasData("山东第一医科大学研...", "http://news.sciencenet.cn/htmlnews/2020/5/439723.shtm"));
        items.add(new AtlasData("威斯康星大学麦迪逊...", "https://www.yicai.com/news/100630664.html"));
        items.add(new AtlasData("英国伦敦大学学院等...", "http://www.bioon.com/article/6755948.html"));
        items.add(new AtlasData("上海交通大学蔡宇伽...", "https://mp.weixin.qq.com/s/Jbl0OljtXP3ke6Z8CmxWIg"));
        items.add(new AtlasData("美国科学家的一项新...", "https://www.thepaper.cn/newsDetail_forward_7474153"));
        items.add(new AtlasData("李彦宏建议针对新冠...", "https://www.thepaper.cn/newsDetail_forward_7476684"));
        items.add(new AtlasData("中科院武汉病毒所石...", "https://mp.weixin.qq.com/s/Nevnd4l4Q76utWziSyT0tg"));
        items.add(new AtlasData("英国等多国科学家团...", "https://www.thepaper.cn/newsDetail_forward_7482501"));
        items.add(new AtlasData("美国斯坦福大学医学...", "https://www.thepaper.cn/newsDetail_forward_7490930"));
        items.add(new AtlasData("中科院武汉病毒所石...", "https://mp.weixin.qq.com/s/6vTTqc8ajXvqXdY3xvvvFw"));
        items = new ArrayList<>();
        atlasItems.add(items);
        items.add(new AtlasData("世界卫生组织总干事...", "https://www.yicai.com/news/100569374.html"));
        items.add(new AtlasData("英国伦敦大学卫生与...", "http://news.sciencenet.cn/htmlnews/2020/3/437601.shtm"));
        items.add(new AtlasData("中央应对新冠肺炎疫...", "http://china.caixin.com/2020-03-27/101534946.html"));
        items.add(new AtlasData("美国国家过敏和传染...", "https://www.yicai.com/news/100568118.html"));
        items.add(new AtlasData("英国国家重症监护审...", "https://www.yicai.com/news/100568542.html"));
        items.add(new AtlasData("中国科学院副秘书长...", "http://news.sciencenet.cn/htmlnews/2020/3/437520.shtm"));
        items.add(new AtlasData("意大利国家卫生研究...", "http://mil.news.sina.com.cn/2020-03-26/doc-iimxyqwa3365706.shtml"));
        items.add(new AtlasData("世卫组织总干事谭德...", "https://www.yicai.com/news/100565917.html"));
        items.add(new AtlasData("菲律宾碧瑶综合医院...", "https://www.chinaz.com/2020/0325/1120870.shtml"));
        items.add(new AtlasData("美国哥伦比亚大学公...", "https://view.inews.qq.com/a/NEW2020032501969402?uid=&chlid=news_news_top&devid=b3c649e040a8e594&qimei=b3c649e040a8e594&shareto=&from=timeline&openid=o04IBAFmV2iyCl3hmsWM01wqmV24&key=&version=27000c37&devicetype=android-28&wuid=oDdoCtyOo0RXJ4rp5p2XVuF2Ei44&sharer=o04IBAFmV2iyCl3hmsWM01wqmV24"));
        items.add(new AtlasData("赛默飞宣布其诊断检...", "https://www.instrument.com.cn/news/20200324/534533.shtml"));
        items.add(new AtlasData("全球疫情流行趋势已...", "https://mp.weixin.qq.com/s/OWkSm_3ZaVnfgWC4RZAaDg"));
        items.add(new AtlasData("特朗普在白宫举行的...", "https://www.yicai.com/news/100557024.html"));
        items.add(new AtlasData("中国疾控中心研究员...", "https://www.yicai.com/news/100557851.html"));
        items.add(new AtlasData("多份报告称动物园存...", "https://www.yicai.com/news/100553576.html"));
        items.add(new AtlasData("美国发布100页抗...", "https://view.inews.qq.com/k/20200318A072I000?openid=o04IBAOgPA9j-qhuvbLoSS3-dfwA&key=&version=27000c36&devicetype=android-29&wuid=oDdoCt87z_gbnJOautmLj-5Pew_g&sharer=o04IBAOgPA9j-qhuvbLoSS3-dfwA&uid=&shareto="));
        items.add(new AtlasData("美国国家过敏和传染...", "https://mp.weixin.qq.com/s/EJy7pzfSILggJ2MzzyuLPg"));
        items.add(new AtlasData("屠呦呦团队指出防范...", "https://mp.weixin.qq.com/s/UpPaxJ1xXUiwfE8_OMUqoA"));
        items.add(new AtlasData("世界卫生组织（WH...", "https://www.yicai.com/news/100551296.html"));
        items.add(new AtlasData("世界顶级期刊《科学...", "https://mp.weixin.qq.com/s/Idhk1FODFIvjG9TcznyhtA"));
        items.add(new AtlasData("美国国家过敏和传染...", "https://2019-ncov.aminer.cn/details?id=5448a76fdabfae87b7e5ac64"));
        items.add(new AtlasData("世卫组织宣布新冠肺...", "http://www.bjnews.com.cn/feature/2020/03/12/702445.html"));
        items.add(new AtlasData("世界卫生组织助理总...", "https://www.fool.com/investing/2020/02/24/gilead-antiviral-drug-shows-the-most-potential-for.aspx"));
        items.add(new AtlasData("世界卫生组织称疫情...", "http://stm.las.ac.cn/STMonitor/qbwnew/bianyi_recordshow.htm?id=36172&parentPageId=1582877461415&serverId=172&controlType="));
        items.add(new AtlasData("世卫专家称中国方法...", "https://www.linkresearcher.com/information/c13358a3-a133-462e-b150-73e6a6e5cb4f"));
        items.add(new AtlasData("美国乔治亚南方大学...", "https://www.medrxiv.org/content/10.1101/2020.02.05.20020750v3"));
        items.add(new AtlasData("《中华流行病学》杂...", "https://m.yicai.com/news/100510208.html"));
        items.add(new AtlasData("AI 辅助诊断新冠...", "https://www.gooyi.net/znyj/121269.html"));
        items.add(new AtlasData("加拿大首例确诊的2...", "https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)30370-6/fulltext"));
        items.add(new AtlasData("湖北将“临床诊断”...", "http://www.xinhuanet.com/politics/2020-02/13/c_1125568674.htm"));
        items.add(new AtlasData("世界卫生组织（WH...", "http://finance.sina.com.cn/china/gncj/2020-01-31/doc-iimxyqvy9209145.shtml"));
        items.add(new AtlasData("《柳叶刀》主编理查...", "https://mp.weixin.qq.com/s/vW_uiY6KVbgnEX26PGjvig"));
        items.add(new AtlasData("美国传染病专家福奇...", "https://www.yicai.com/news/100576064.html"));
        items.add(new AtlasData("国疾控中心主任罗伯...", "http://news.sciencenet.cn/htmlnews/2020/4/437826.shtm"));
        items.add(new AtlasData("美国白宫冠状病毒应...", "http://news.sciencenet.cn/htmlnews/2020/4/437826.shtm"));
        items.add(new AtlasData("武汉病毒所石正丽：...", "https://new.qq.com/omn/20200320/20200320A08BR600.html"));
        items.add(new AtlasData("中国疾控中心冯录召...", "https://baijiahao.baidu.com/s?id=1661671358965411310&wfr=spider&for=pc"));
        items.add(new AtlasData("中国疾控中心专家吴...", "https://new.qq.com/omn/20200214/20200214A0OI3M00.html"));
        items.add(new AtlasData("世界卫生组织总干事...", "https://www.yicai.com/news/100581871.html"));
        items.add(new AtlasData("纽约城市学院国际关...", "https://www.yicai.com/news/100581360.html"));
        items.add(new AtlasData("《纽约时报》著名专...", "http://www.sci666.com.cn/47720.html"));
        items.add(new AtlasData("世界卫生组织总干事...", "https://www.yicai.com/news/100587388.html"));
        items.add(new AtlasData("《自然》杂志在题为...", "http://news.sciencenet.cn/htmlnews/2020/4/438155.shtm"));
        items.add(new AtlasData("美国新泽西州罗格斯...", "https://www.yicai.com/news/100594477.html"));
        items.add(new AtlasData("美国哈佛大学研究人...", "https://www.yicai.com/news/100594469.html"));
        items.add(new AtlasData("加州大学旧金山分校...", "http://www.sci666.com.cn/49236.html"));
        items.add(new AtlasData("美国疾病控制和预防...", "https://www.thepaper.cn/newsDetail_forward_6995658"));
        items.add(new AtlasData("香港大学世卫传染病...", "http://news.sciencenet.cn/htmlnews/2020/4/438476.shtm"));
        items.add(new AtlasData("世界卫生组织发布的...", "https://www.yicai.com/news/100595551.html"));
        items.add(new AtlasData("世卫组织卫生紧急项...", "https://www.yicai.com/news/100595411.html"));
        items.add(new AtlasData("英国卫生部表示，该...", "https://www.thepaper.cn/newsDetail_forward_7067556"));
        items.add(new AtlasData("世界气象组织发布公...", "https://www.thepaper.cn/newsDetail_forward_7100206"));
        items.add(new AtlasData("最新公布的尸检结果...", "https://www.yicai.com/news/100606335.html"));
        items.add(new AtlasData("英国政府表示，英国...", "https://www.yicai.com/news/100605621.html"));
        items.add(new AtlasData("世卫组织表示现有证...", "http://news.sciencenet.cn/htmlnews/2020/4/438726.shtm"));
        items.add(new AtlasData("美国加州圣克拉拉县...", "http://news.sciencenet.cn/htmlnews/2020/4/438987.shtm"));
        items.add(new AtlasData("美国首例死亡病例尸...", "https://www.thepaper.cn/newsDetail_forward_7150117"));
        items.add(new AtlasData("荷兰出现貂感染新冠...", "https://www.thepaper.cn/newsDetail_forward_7160464"));
        items.add(new AtlasData("美国路易斯安那州立...", "https://mp.weixin.qq.com/s/q6x71y87aTK_5fC7FYjVNg"));
        items.add(new AtlasData("美国疾控中心研究人...", "https://baijiahao.baidu.com/s?id=1665625037898891089&wfr=spider&for=pc"));
        items.add(new AtlasData("美国明尼苏达大学传...", "https://www.thepaper.cn/newsDetail_forward_7234123"));
        items.add(new AtlasData("加拿大官方反对党保...", "https://3g.163.com/3g/article_cambrian/FAG6S4E50514EMD3.html"));
        items.add(new AtlasData("美国食品药品监督管...", "http://www.caixin.com/2020-05-09/101552104.html"));
        items.add(new AtlasData("世卫组织卫生紧急项...", "http://news.sciencenet.cn/htmlnews/2020/5/439504.shtm"));
        items.add(new AtlasData("日本NHK实验揭秘...", "https://3g.163.com/news/article_cambrian/FCI27IAF0520PKI6.html?from=history-back-list"));
        items.add(new AtlasData("世卫组织紧急项目负...", "http://news.sciencenet.cn/htmlnews/2020/5/439715.shtm"));
        items.add(new AtlasData("世卫组织科学家控制...", "http://news.sciencenet.cn/htmlnews/2020/5/439784.shtm"));
        items.add(new AtlasData("世界卫生组织(Wo...", "https://mp.weixin.qq.com/s/uYJtA7h1fVm6g9k-t2Usfw"));
        items = new ArrayList<>();
        atlasItems.add(items);
        items.add(new AtlasData("复旦大学公共卫生临...", "https://www.yicai.com/news/100570119.html"));
        items.add(new AtlasData("管轶教授发现，从走...", "https://mp.weixin.qq.com/s/qB-UWWXECpfoku7vlpCoAw"));
        items.add(new AtlasData("意大利14家研究中...", "http://mil.news.sina.com.cn/2020-03-26/doc-iimxyqwa3224069.shtml"));
        items.add(new AtlasData("荷兰，澳大利亚，德...", "https://mp.weixin.qq.com/s/dRpGH-c_qAYpxZJEgqo-KA"));
        items.add(new AtlasData("云南大学张志刚团队...", "https://mp.weixin.qq.com/s/OdoaKiPZMTzePvBvQqtFSQ"));
        items.add(new AtlasData("德国吕贝克大学生物...", "https://mp.weixin.qq.com/s/C6Xh4xj9846EQk4pBafi0g"));
        items.add(new AtlasData("香港大学研究人员评...", "http://www.sci666.com.cn/45240.html"));
        items.add(new AtlasData("澳大利亚墨尔本大学...", "https://mp.weixin.qq.com/s/X3q7J3dUlL3FGOvc4AT37Q"));
        items.add(new AtlasData("新加坡多个研究机构...", "http://science.caixin.com/2020-03-16/101529007.html"));
        items.add(new AtlasData("首都机场设置处置专...", "http://news.sina.com.cn/c/2020-03-15/doc-iimxyqwa0658133.shtml"));
        items.add(new AtlasData("重庆大学医学院等研...", "https://www.yicai.com/news/100548984.html"));
        items.add(new AtlasData("钟南山所言“疫情爆...", "https://s1.uczzd.cn/webview/news?app=uc-iflow&aid=13667529600510035627&cid=100&zzd_from=uc-iflow&uc_param_str=dndsfrvesvntnwpfgicp&recoid=2809584386276931574&rd_type=share&sp_gz=0&pagetype=share&btifl=100&uc_share_depth=1"));
        items.add(new AtlasData("我国多家科研机构联...", "http://www.sci666.com.cn/41966.html"));
        items.add(new AtlasData("北京市疾控中心团队...", "http://www.sci666.com.cn/42378.html"));
        items.add(new AtlasData("Rolf Hilg...", "https://www.worldhealth.net/news/new-compounds-fight-multiple-viruses/"));
        items.add(new AtlasData("科学家们正在努力找...", "https://www.nature.com/articles/d41586-020-00548-w"));
        items.add(new AtlasData("利普金教授团队通过...", "http://finance.eastmoney.com/a/202002271399537953.html"));
        items.add(new AtlasData("继香港大学管轶公布...", "https://m.yicai.com/news/100516286.html"));
        items.add(new AtlasData("汕头大学粤港新发传...", "http://china.caixin.com/2020-02-20/101518173.html?cxw=Android&Sfrom=Wechat&originReferrer=Androidshare"));
        items.add(new AtlasData("义翘神州在拿到新型...", "https://m.yicai.com/news/100509339.html"));
        items.add(new AtlasData("新型冠状病毒潜在中...", "http://m.xinhuanet.com/gd/2020-02/08/c_1125544802.htm"));
        items.add(new AtlasData("华南农业大学：穿山...", "https://new.qq.com/omn/20200207/20200207A013D400.html?pgv_ref=aio2015&ptlang=2052"));
        items.add(new AtlasData("谷歌研究副总裁、互...", "http://cache.baiducontent.com/c?m=9f65cb4a8c8507ed19fa950d100b9131480e97634b968b492cc3933fc23904564711b2e73a790d04d1c57e7001d94b5dfdf04073341e76eacadf883c86e0cd6264cb6267761c864410d419b8cb31649b66cf04fdea44a7ecff6acef48ec4df250e9408412dc0&p=8e6dc95dcc904ead08e2957d7f7a&newp=c6648f16d9c10bf511bd9b7f0e4792695912c10e3dd4c44324b9d71fd325001c1b69e3b823281603d4c6786c15e9241dbdb239256b556aedd2&user=baidu&fm=sc&query=John+Oliver&qid=d36c190100065c48&p1=4"));
        items.add(new AtlasData("复旦大学公共卫生临...", "http://sa.sogou.com/sgsearch/sgs_tc_news.php?req=g7R1OAufnvJwjD0XwqeOHSw2CRPeSZXOiOqzR7RDmvw=&f_type=feed"));
        items.add(new AtlasData("德国科研人员成功破...", "https://new.qq.com/omn/20200326/20200326A02FWQ00.html"));
        items.add(new AtlasData("管轶团队：马来亚穿...", "https://www.360kuai.com/pc/9902bc682a41d2f35?cota=3&kuai_so=1&sign=360_57c3bbd1&refer_scene=so_1"));
        items.add(new AtlasData("张志刚称，由于穿山...", "https://2019-ncov.aminer.cn/details?id=562beab845cedb3398b8bb46"));
        items.add(new AtlasData("中国工程院院士、华...", "https://baijiahao.baidu.com/s?id=1658163640247513143&wfr=spider&for=pc"));
        items.add(new AtlasData("澳大利亚莫纳什大学...", "http://sa.sogou.com/sgsearch/sgs_tc_news.php?req=7ly-zJ5UyDATYuopNcU1HwOChnr8sG0ehVeUSRee-TY=&f_type=feed"));
        items.add(new AtlasData("荷兰等国家科学研究...", "https://www.yicai.com/news/100581186.html"));
        items.add(new AtlasData("美国纽约市布朗克斯...", "http://news.sciencenet.cn/htmlnews/2020/4/437999.shtm"));
        items.add(new AtlasData("香港大学Benja...", "https://mp.weixin.qq.com/s/cfUiXVi4NgdzardISyfLcA"));
        items.add(new AtlasData("欧洲研究团队提出了...", "https://mp.weixin.qq.com/s/EwYxGeg-uiAjDb7zphMuNA"));
        items.add(new AtlasData("韩国基础科学研究所...", "https://mp.weixin.qq.com/s/xUhKOfuzRbH3_tr4aHuCzg"));
        items.add(new AtlasData("韩国疾病管理本部与...", "https://www.yicai.com/news/100585916.html"));
        items.add(new AtlasData("香港相达生物科技公...", "https://www.yicai.com/news/100587810.html"));
        items.add(new AtlasData("英国研究人员按照进...", "https://sa.sogou.com/sgsearch/sgs_tc_news.php?req=U4FOcuKAZaCJKPQ7rPjfEeSCopdYyOkQwdZEd2iMbGs=&f_type=feed"));
        items.add(new AtlasData("意大利锡耶纳大学的...", "https://mp.weixin.qq.com/s/lBBkJAS57XiTEuDhuLIJHQ"));
        items.add(new AtlasData("澳大利亚研究人员研...", "http://news.sciencenet.cn/htmlnews/2020/4/438234.shtm"));
        items.add(new AtlasData("北京大学来鲁华团队...", "https://mp.weixin.qq.com/s/-RQla263RBDtXz29PmgiGQ"));
        items.add(new AtlasData("欧洲相关研究人员发...", "http://science.caixin.com/2020-04-14/101542339.html"));
        items.add(new AtlasData("渥太华大学生物学教...", "https://mp.weixin.qq.com/s/i_k6EhivZ0RXJFm4i6h_3A"));
        items.add(new AtlasData("广东省疾病预防控制...", "https://mp.weixin.qq.com/s/93tB4QYE2EdtS3kxM_LVjw"));
        items.add(new AtlasData("澳大利亚和中国台湾...", "https://mp.weixin.qq.com/s/QI3NCjmBSseeTheuUGvL_Q"));
        items.add(new AtlasData("美国加利福尼亚大学...", "https://mp.weixin.qq.com/s/of16t-Eq0Kmc41oGBt9i3w"));
        items.add(new AtlasData("意大利多家科研机构...", "https://mp.weixin.qq.com/s/ecFYDSNck8b8IB2TnC6H1A"));
        items.add(new AtlasData("中国专家发现部分病...", "https://www.yicai.com/news/100609280.html"));
        items.add(new AtlasData("加州大学旧金山分校...", "https://mp.weixin.qq.com/s/nAAGRhB_9y7ID4MIvTA9mA"));
        items.add(new AtlasData("欧洲和北美的多个研...", "https://mp.weixin.qq.com/s/V33rM1iMyygv9J514MMT1A"));
        items.add(new AtlasData("一国际研究团队对西...", "https://www.thepaper.cn/newsDetail_forward_7160034"));
        items.add(new AtlasData("美国研究人员标记和...", "https://mp.weixin.qq.com/s/ymLTiKtd7FlnluKVo4FY8g"));
        items.add(new AtlasData("Ralph Bar...", "https://mp.weixin.qq.com/s/iQB9jnu_ITEqPdL2VcOmHg"));
        items.add(new AtlasData("澳大利亚墨尔本大学...", "http://news.sciencenet.cn/htmlnews/2020/5/439302.shtm"));
        items.add(new AtlasData("目前普遍认可的是，...", "https://news.sina.cn/gj/2020-04-15/detail-iircuyvh7974077.d.html?wm=6142"));
        items.add(new AtlasData("复旦大学研究人员利...", "https://mp.weixin.qq.com/s/lyDyxYA1JtUWhi7eKRnc0A"));
        items.add(new AtlasData("华南农业大学研究人...", "https://mp.weixin.qq.com/s/8nY03hderrmJz0KPr0Fqtg"));
        items.add(new AtlasData("美国洛斯阿拉莫斯国...", "https://www.thepaper.cn/newsDetail_forward_7305880"));
        items.add(new AtlasData("英国约翰逊政府首次...", "https://www.thepaper.cn/newsDetail_forward_7359209"));
        items.add(new AtlasData("以色列沙米尔医学中...", "http://news.sciencenet.cn/htmlnews/2020/5/439766.shtm"));
        items.add(new AtlasData("美国疾病控制和预防...", "tps://www.thepaper.cn/newsDetail_forward_7458395"));
        items = new ArrayList<>();
        atlasItems.add(items);
        items.add(new AtlasData("湖北省卫生健康委员...", "https://www.yicai.com/news/100568517.html"));
        items.add(new AtlasData("科技部副部长徐南平...", "http://news.sciencenet.cn/htmlnews/2020/3/437478.shtm"));
        items.add(new AtlasData("复旦大学姜世勃指出...", "https://mp.weixin.qq.com/s/hRkt-C87Wna-e7EP7izqqQ"));
        items.add(new AtlasData("科技部生物中心主任...", "https://www.yicai.com/news/100552273.html"));
        items.add(new AtlasData("国家卫健委新闻发言...", "https://www.yicai.com/news/100550337.html"));
        items.add(new AtlasData("上海市卫生健康委副...", "https://www.yicai.com/news/100550340.html"));
        items.add(new AtlasData("国家自然科学基金委...", "http://www.nsfc.gov.cn/publish/portal0/tab568/info77534.htm"));
        items.add(new AtlasData("Covid-19爆...", "https://mp.weixin.qq.com/s/nJ10m9QQtyZqgfukxlaQ6g"));
        items.add(new AtlasData("中国工程院院士、华...", "http://news.sina.com.cn/c/2020-03-10/doc-iimxyqvz9225387.shtml"));
        items.add(new AtlasData("国家卫生健康委、人...", "https://mp.weixin.qq.com/s/hG_fl2pxZvwkbmVQVolKBw"));
        items.add(new AtlasData("广东推出“战疫人才...", "http://www.gov.cn/xinwen/2020-02/15/content_5479164.htm"));
        items.add(new AtlasData("陕西省首批8个针对...", "http://news.cnwest.com/xian/a/2020/02/06/18443866.html"));
        items.add(new AtlasData("山西省紧急立项14...", "http://www.gov.cn:8080/xinwen/2020-02/06/content_5475128.htm"));
        items.add(new AtlasData("广西启动首批战“疫...", "https://new.qq.com/omn/20200206/20200206A0QUDP00.html"));
        items.add(new AtlasData("战疫情 成都首批8...", "http://sc.china.com.cn/2020/kejiao_dongtai_0131/352266.html"));
        items.add(new AtlasData("辽宁省首批8个应急...", "http://www.ln.gov.cn/zfxx/msrd/202001/t20200125_3729059.html"));
        items.add(new AtlasData("科技部副部长徐南平...", "https://mp.weixin.qq.com/s/7iWTsVc4AgFnRCzLB_fl-w"));
        items.add(new AtlasData("Google正式宣...", "https://baijiahao.baidu.com/s?id=1662732250271384943&wfr=spider&for=pc"));
        items.add(new AtlasData("清华大学万科公共卫...", "http://news.tsinghua.edu.cn/publish/thunews/9648/2020/20200402141404130235216/20200402141404130235216_.html"));
        items.add(new AtlasData("董家鸿说，因应新冠...", "http://www.chinanews.com/sh/2020/03-16/9127385.shtml"));
        items.add(new AtlasData("重磅发布！高福等获...", "https://3g.163.com/3g/article_cambrian/F76V26FL05329KGN.html"));
        items.add(new AtlasData("新型冠状病毒肺炎背...", "http://cn.chinadaily.com.cn/a/202002/16/WS5e491f52a3107bb6b579ff85.html"));
        items.add(new AtlasData("科技部安排3.2亿...", "http://news.sciencenet.cn/htmlnews/2020/4/437903.shtm"));
        items.add(new AtlasData("世界卫生组织总干事...", "http://news.sciencenet.cn/htmlnews/2020/4/437956.shtm"));
        items.add(new AtlasData("斯坦福大学教授戴维...", "https://www.thepaper.cn/newsDetail_forward_6939751"));
        items.add(new AtlasData("科技部生物中心副主...", "https://www.yicai.com/news/100592541.html"));
        items.add(new AtlasData("广州市医疗保障局发...", "https://www.thepaper.cn/newsDetail_forward_7148401"));
        items.add(new AtlasData("世卫组织重新评估新...", "http://international.caixin.com/2020-05-02/101549852.html"));
        items.add(new AtlasData("中国工程院院士张伯...", "https://new.qq.com/omn/20200424/20200424A042XB00.html"));
        items = new ArrayList<>();
        atlasItems.add(items);
        items.add(new AtlasData("俄罗斯联邦生物医药...", "https://baijiahao.baidu.com/s?id=1662416887538338964&wfr=spider&for=pc"));
        items.add(new AtlasData("钟南山院士指出国内...", "https://www.yicai.com/news/100568725.html"));
        items.add(new AtlasData("德国吕贝克大学等机...", "https://sa.sogou.com/sgsearch/sgs_tc_news.php?req=jIw5znUDqjaOH6H29IQ7BLQCO0TN7Yzrt7wc5Z67jKQ=&appinfo=SgL8QvtGkoc7xfT9%2Bcv6Kf5gqOP8dJW0uJ74GEMEamxsGrsyREl6eqfCQcuGrKA4SCZFjqFvODWhrsI5ft49Nj3QNczJfUuO7DnS5FOQ%2F2gL849nZsKnV8yFpXdBKjPNER1Gyv%2FzsDPo0ISob0Kfg%2FBjE04TZWfzYaeX7e1jjroKGe47Yid6vQuusjQSPnjHFkttIjxEEKLt4qwwBClZx09%2Bcv9OG19yFnupUBXMKj%2B1sWASy337Q7papDQ%2B6p7MotTzdFTgNRUuF6Syq%2FIHN090tiHO7i7Ria%2FH2bgbOzCi3ZTIEPaXBa3KS76O%2BT0mb5TY8V%2BS6x%2Feo1nMd8k6joWglRYqBpkCzY8ODcECIIlDmSi%2BlaZu22YJy5O%2FD99e7nq3ob3Dry9glCvWXdP99F75kcO6pMvpOWU6uY2JG1VKTVXIpmCUa5XrBDlYOGWtg4qB9P%2BAO3wIcPc0ljZV6Z9VCRFEU%2Bwk3%2FDvvg5c62HM2zvFdL8pDcd5L2f8pvmUGMM%2FBDq9QXnTZjTOFu5obTUCdEUR4kBo3121ef4sF9vYOhYPktPDFPjtD1Yinwv%2B1h4bmPzIEb13%2B%2BPxIX7EJv9UYApG2kBtGHkUtZjk9Em2BBvk62%2BdM6Jyrl%2FlrRh0rq6mKP%2BB7Dj0mtLdPUNx%2BJ6iPureOp%2Bu29Dy6uLGWOTlmYPcTpIwocAXBsPz7M53WB%2Bnyr250yffXbiknMabJvZQK5fJXHvmDvFT7pk%2FPYmI4SjYOFMr409TAV5Jlkg%2FzUfVzDW4dC1t80mMdTTX4YZWRzVLei%2FKHwzxPPnnzOMgQUJn3zzOfdsv%2BuEJQGT5rvcW950ySyxIZXeAx1yPDNtMQ3bCiv7a7k2yVXw56%2FFDwKtW9PAT%2Bz8NFRfi9ZutaS0m2GVj87Bxp2lI2fxpDeXk5pL%2BimH5imISt9klZLc%2B9wTN%2B1wgnIuzyO%2FUryBhBIwDyTgd3j42RKEbfaI%2FcZzkO5aCTbswUpuuWRZmLwB7%2B41PweAvodPloBKfWen%2B%2FV7UrysSZpsVDZB6vi4eJ3uB3hXmdfH6eq8%2FrfeXma8fVBgQZPkuVmDyygwFB3UEHFS9naGmkI7gLPAKJvB1KCAc7gHV6UoIRgcbcEQs4a6hGppzXPtDhnH6wJTsmTu7Kya2AVH1moGLPhvM9KjdqDuGPwHtfSpkuPLKw541Cm9kpa3j4F%2FAL5hLTB%2FU6OQh8QoBGm3YVcJuHXEECHLacpiyewEgWd6Ytkv2xNfAzERgA84oKnvzVFcpRm2VFHQCB1TpiWgEsySUe%2B0sEthWd%2B8lJLjzzX0lbMtrdml2s5pmRR8mZGj%2FKw74zqigSpqjWbu2DTIuWJyOf5wL%2BFsmrRkmF48DyGdUB%2F4tzQzZ170%3D&mat=0"));
        items.add(new AtlasData("广州医科大学呼吸疾...", "http://sa.sogou.com/sgsearch/sgs_tc_news.php?req=BWM_l67Z7f9OlEPPI-keI_3mA8rmtK-IP34W-7rKQxU=&f_type=feed&appinfo=SgL8QvtGkoc7xfT9%2Bcv6Kf5gqOP8dJW0uJ74GEMEamxsGrsyREl6eqfCQcuGrKA4SCZFjqFvODWhrsI5ft49Nj3QNczJfUuO7DnS5FOQ%2F2gL849nZsKnV8yFpXdBKjPNER1Gyv%2FzsDPo0ISob0Kfg%2FBjE04TZWfzYaeX7e1jjroKGe47Yid6vQuusjQSPnjHFkttIjxEEKLt4qwwBClZx09%2Bcv9OG19yFnupUBXMKj%2B1sWASy337Q7papDQ%2B6p7MotTzdFTgNRUuF6Syq%2FIHN090tiHO7i7Ria%2FH2bgbOzCi3ZTIEPaXBa3KS76O%2BT0mb5TY8V%2BS6x%2Feo1nMd8k6joWglRYqBpkCzY8ODcECIIlDmSi%2BlaZu22YJy5O%2FD99e7nq3ob3Dry9glCvWXdP99F75kcO6pMvpOWU6uY2JG1VKTVXIpmCUa5XrBDlYOGWtg4qB9P%2BAO3wIcPc0ljZV6Z9VCRFEU%2Bwk3%2FDvvg5c62HM2zvFdL8pDcd5L2f8pvmUGMM%2FBDq9QXnTZjTOFu5obTUCdEUR4kBo3121ef4sF9vYOhYPktPDFPjtD1Yinwv%2B1h4bmPzIEb13%2B%2BPxIX7EJv9UYApG2kBtGHkUtZjk9Em2BBvk62%2BdM6Jyrl%2FlrRh0rq6mKP%2BB7Dj0mtLdPUNx%2BJ6iPureOp%2Bu29Dy6uLGWOTlmYPcTpIwocAXBsPz7M53WB%2Bnyr250yffXbiknMabJvZQK5fJXHvmDvFT7pk%2FPYmI4SjYOFMr409TAV5Jlkg%2FzUfVzDW4dC1t80mMdTTX4YZWRzVLei%2FKHwzxPPnnzOMgQUJn3zzOfdsv%2BuEJQGT5rvcW950ySyxIZXeAx1yPDNtMQ3bCiv7a7k2yVXw56%2FFDwKtW9PAT%2Bz8NFRfi9ZutaS0m2GVj87Bxp2lI2fxpDeXk5pL%2BimH5imISt9klZLc%2B9wTN%2B1wgnIuzyO%2FUryBhBIwDyTgd3j42RKEbfaI%2FcZzkO5aCTbswUpuuWRZmLwB7%2B41PweAvodPloBKfWen%2B%2FV7UrysSZpsVDZB6vi4eJ3uB3hXmdfH6eq8%2FrfeXma8fVBgQZPkuVmDyygwFB3UEHFS9naGmkI7gLPAKJvB1KCAc7gHV6UoIRgcbcEQs4a6hGppzXPtDhnH6wJTsmTu7Kya2AVH1moGLPhvM9KjdqDuGPwHtfSpkuPLKw541Cm9kpa3j4F%2FAL5hLTB%2FU6OQh8QoBGm3YVcJuHXEECHLacpiyewEgWd6Ytkv2xNfAzERgA84oKnvzVFcpRm2VFHQCB1TpiWgEsySUe%2B0sEthWd%2B8lJLjzzX0lbMtrdml2s5pmRR8mZGj%2FKw74zqigSpqjWbu2DTIuWJyOf5wL%2BFsmrRkmF48DyGdUB%2F4tzQzZ170%3D&mat=0"));
        items.add(new AtlasData("清华大学饶子和研究...", "https://mp.weixin.qq.com/s/Kyt0i-klEmCJP_frsVCnkA"));
        items.add(new AtlasData("北京大学第一医院感...", "https://www.yicai.com/news/100557833.html"));
        items.add(new AtlasData("上海科技大学-清华...", "http://www.sci666.com.cn/45129.html"));
        items.add(new AtlasData("饶子和院士等团队发...", "https://mp.weixin.qq.com/s/O36by4zbTQoZ2K_5Qvu9qw"));
        items.add(new AtlasData("华中科技大学刘亚兰...", "https://mp.weixin.qq.com/s/rxncZ8S4mwu6H9BjgQ_xKg"));
        items.add(new AtlasData("空军军医大学陈志南...", "http://www.sci666.com.cn/44103.html"));
        items.add(new AtlasData("清华大学、江苏省疾...", "http://www.sci666.com.cn/43796.html"));
        items.add(new AtlasData("曾为SARS研发的...", "https://www.linkresearcher.com/information/26a0ba6e-95ab-4ab5-a893-2886b2c4a896"));
        items.add(new AtlasData("第四军医大学陈志南...", "https://mp.weixin.qq.com/s/J-6mwSlDdrfKrAvmda1vZQ"));
        items.add(new AtlasData("华东理工大学药学院...", "https://mp.weixin.qq.com/s/di2A6bOvaCw81uqjIqCT_Q"));
        items.add(new AtlasData("钟南山院士在首届新...", "https://s2.uczzd.cn/webview/news?app=uc-iflow&aid=10329545262897854039&cid=10520&zzd_from=uc-iflow&uc_param_str=dndsfrvesvntnwpfgicp&recoid=3826645281273837879&rd_type=share&sp_gz=0&pagetype=share&btifl=100&uc_share_depth=1"));
        items.add(new AtlasData("世卫组织在官网“常...", "https://www.aminer.cn/research_report/5e6841f5441141e02bfbaf34?download=false"));
        items.add(new AtlasData("新冠肺炎是一个自限...", "https://mp.weixin.qq.com/s/582ifuPpm4iNi_V7TOijmQ"));
        items.add(new AtlasData("中国科学院院士、解...", "https://news.163.com/20/0305/11/F6V17T580001899O.html"));
        items.add(new AtlasData("病毒感染及其诱导的...", "http://www.sci666.com.cn/40027.html"));
        items.add(new AtlasData("第一例新冠肺炎逝者...", "https://www.yicai.com/news/100525725.html"));
        items.add(new AtlasData("沈阳化工大学应用生...", "http://www.sci666.com.cn/39412.html"));
        items.add(new AtlasData("王辰院士等Lanc...", "https://www.cn-healthcare.com/article/20200226/content-531526.html"));
        items.add(new AtlasData("在开展病毒溯源研究...", "https://m.yicai.com/news/100517472.html"));
        items.add(new AtlasData("哈佛大学、广州呼吸...", "http://www.eol.cn/rencai/202002/t20200220_1712782.shtml"));
        items.add(new AtlasData("在华中科技大学同济...", "http://www.sohu.com/a/373886909_99966956"));
        items.add(new AtlasData("王福生院士团队发布...", "https://www.360kuai.com/pc/9013587592f75e105?cota=3&kuai_so=1&sign=360_e39369d1&refer_scene=so_3"));
        items.add(new AtlasData("张伯礼院士团队发现...", "https://3g.163.com/jiankang/article/F4Q4D382053402LE.html"));
        items.add(new AtlasData("艾滋病药物可以阻止...", "https://www.tellerreport.com/life/2020-01-28---rolf-hilgenfeld--%22aids-drugs-could-stop-the-coronavirus-outbreak%22-.By7M3L9TbI.html"));
        items.add(new AtlasData("王辰院士、高福院士...", "http://news.bioon.com/article/6749650.html"));
        items.add(new AtlasData("军事医学科学院曹诚...", "https://mp.weixin.qq.com/s/nvQQtx0z8CxR16nZqtV9Jg"));
        items.add(new AtlasData("2020年4月1日...", "http://www.sci666.com.cn/47110.html"));
        items.add(new AtlasData("钟南山院士与广州呼...", "http://news.ycwb.com/2020-03/31/content_731559.htm"));
        items.add(new AtlasData("钟南山院士团队受邀...", "http://news.cyol.com/app/2020-03/31/content_18545449.htm"));
        items.add(new AtlasData("王福生院士发文：新...", "https://news.163.com/20/0305/11/F6V17T580001899O.html"));
        items.add(new AtlasData("卞修武院士：系统解...", "https://xueqiu.com/5828850316/142789841?page=2"));
        items.add(new AtlasData("中科院院士卞修武：...", "https://www.sohu.com/a/377172617_260616"));
        items.add(new AtlasData("中国药学会副理事长...", "https://baijiahao.baidu.com/s?id=1662278304690491592&wfr=spider&for=pc"));
        items.add(new AtlasData("中国科学院院士、陆...", "https://new.qq.com/omn/20200311/20200311A0MCHF00.html"));
        items.add(new AtlasData("陈焕春：近期又发现...", "http://n.eastday.com/pnews/1581256984017319"));
        items.add(new AtlasData("卞修武：依法规范开...", "http://news.sciencenet.cn/sbhtmlnews/2020/2/353400.shtm"));
        items.add(new AtlasData("纽约神经外科“大牛...", "https://www.sohu.com/a/384876754_456062"));
        items.add(new AtlasData("第四军医大学陈志南...", "https://3g.163.com/news/article_cambrian/F7S5AMIO051480KF.html"));
        items.add(new AtlasData("饶子和院士等人新研...", "https://news.sina.com.cn/o/2020-03-20/doc-iimxxsth0604315.shtml"));
        items.add(new AtlasData("饶子和精英团队等取...", "https://www.360kuai.com/pc/986a53d366644022a?cota=3&kuai_so=1&sign=360_e39369d1&refer_scene=so_54"));
        items.add(new AtlasData("2020年2月17...", "https://www.thepaper.cn/newsDetail_forward_6056885"));
        items.add(new AtlasData("火神山新型冠状病毒...", "http://www.ddsb.cn/news/20200203/23302186395.html"));
        items.add(new AtlasData("港大医学院院长梁卓...", "http://finance.eastmoney.com/a/202002011368982675.html"));
        items.add(new AtlasData("匹兹堡大学医学院基...", "https://mp.weixin.qq.com/s/vhv0_X9d5aJfwH7O6izMtQ"));
        items.add(new AtlasData("上海科技大学饶子和...", "https://mp.weixin.qq.com/s/HvynO7XlPRx80rqlpl3GWQ"));
        items.add(new AtlasData("加拿大阿尔伯塔大学...", "https://mp.weixin.qq.com/s/SDyNjUTzaWYDlVMkZBs1AQ"));
        items.add(new AtlasData("饶子和院士团队率先...", "https://mp.weixin.qq.com/s/a_CVyPps1TwRBSZf4qRDDA"));
        items.add(new AtlasData("中国科学院大连化学...", "http://news.sciencenet.cn/htmlnews/2020/4/438297.shtm"));
        items.add(new AtlasData("中科院上海药物所许...", "https://mp.weixin.qq.com/s/UCuQ7P9zP2DFXGNe6VgXvA"));
        items.add(new AtlasData("北京大学援鄂抗疫国...", "https://www.thepaper.cn/newsDetail_forward_6969017"));
        items.add(new AtlasData("中国科学院上海药物...", "https://mp.weixin.qq.com/s/YqaVBw6IAe1lrcqnJ_fp-w"));
        items.add(new AtlasData("清华大学医学院饶子...", "https://mp.weixin.qq.com/s/d3gu_jMCfB4atnxZejJHdQ"));
        items.add(new AtlasData("瑞典一研究小组开发...", "http://news.sciencenet.cn/htmlnews/2020/4/438748.shtm"));
        items.add(new AtlasData("高福院士团队研究描...", "https://mp.weixin.qq.com/s/UmYX1NX6xcIB5hcAY37nsw"));
        items.add(new AtlasData("金斯瑞生物与美国西...", "https://finance.sina.cn/stock/relnews/hk/2020-04-28/detail-iircuyvi0342448.d.html?vt=4"));
        items.add(new AtlasData("张文宏教授团队在 ...", "https://mp.weixin.qq.com/s/OlOxYK3ldoyOwIaihNBXTQ"));
        items.add(new AtlasData("陆军军医大学卞修教...", "https://3g.163.com/jiankang/article_cambrian/FBCBOUOJ05329KGN.html"));
        items.add(new AtlasData("清华大学饶子和院士...", "https://www.thepaper.cn/newsDetail_forward_7188862"));
        items.add(new AtlasData("清华大学医学院饶子...", "https://www.thepaper.cn/newsDetail_forward_7100030"));
        items.add(new AtlasData("中科院上海药研所发...", "http://news.sina.com.cn/c/2020-04-23/doc-iirczymi7860248.shtml"));
        items.add(new AtlasData("袁国勇院士团队系统...", "https://3g.163.com/news/article_cambrian/FAS442RG05349C3G.html"));
        items.add(new AtlasData("中国科学院院士王福...", "http://news.sina.com.cn/c/2020-04-19/doc-iircuyvh8685723.shtml"));
        items.add(new AtlasData("英国南安普敦大学研...", "https://mp.weixin.qq.com/s/xb5Xa1y84NP-830HoVB-jA"));
        items.add(new AtlasData("中国疾控中心主任高...", "http://news.sciencenet.cn/htmlnews/2020/5/439517.shtm"));
        items.add(new AtlasData("西湖大学周强团队利...", "https://mp.weixin.qq.com/s/aP7sOPt84VAo8qGi3EjZbg"));
        items.add(new AtlasData("美国明尼苏达大学的...", "https://mp.weixin.qq.com/s/SH6P0tjhiVmSW1dkzQbaSw"));
        items.add(new AtlasData("复旦大学基础医学院...", "https://mp.weixin.qq.com/s/mm3jQoFatjbYByYMTGoXGA"));
        items.add(new AtlasData("钟南山院士团队对四...", "http://news.sciencenet.cn/htmlnews/2020/5/440243.shtm"));

    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_news_cluster);
        initView();
        expandableListView = (ExpandableListView) findViewById(R.id.cluster_expandable_list);
        expandableListView.setAdapter(new AtlasExpandableListAdapter(categoryNames, categorySizes, atlasItems));
        //设置分组的监听
        expandableListView.setOnGroupClickListener(new ExpandableListView.OnGroupClickListener() {
            @Override
            public boolean onGroupClick(ExpandableListView parent, View v, int groupPosition, long id) {
                return false;
            }
        });
        //设置子项布局监听
        expandableListView.setOnChildClickListener(new ExpandableListView.OnChildClickListener() {
            @Override
            public boolean onChildClick(ExpandableListView parent, View v, int groupPosition, int childPosition, long id) {
                return true;
            }
        });
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
    }

}
